"""
Full script that integrates BUML class diagrams with object diagrams generated from Alloy XML.

This script:
1. Reads the instance XML file generated by Alloy Analyzer
2. Reads the original BUML model (class diagram)
3. Generates the object diagram using the AlloyToBesserConverter
4. Combines both into a complete BUML file with class + objects + project
"""

import logging
import os
import re
import sys
import xml.etree.ElementTree as ET

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__) 



class AlloyToBesserConverter:
    """Converts Alloy XML instances to BESSER objects."""

    def __init__(self, xml_file: str):
        """
        Initializes the converter with the given Alloy XML file.
        
        Args:
            xml_file: Path to Alloy XML file
        """
        self.xml_file = xml_file
        self.tree = ET.parse(xml_file)
        self.root = self.tree.getroot()

        # Data structures to store parsed information
        self.signatures = {}  # sig_id -> {label, atoms}
        self.fields = {}  # field_id -> {label, parent_id, tuples}
        self.atoms_by_sig = {}  # sig_label -> [atoms]
        self.builtin_sigs = {'seq/Int', 'Int', 'String', 'univ', 'boolean/Bool', 
                            'boolean/True', 'boolean/False'}
        
    def parse_xml(self):
        """Parses the Alloy XML file and extracts signatures, fields, and atoms."""

        # Parse signatures
        for sig in self.root.findall('.//sig'):
            sig_id = sig.get('ID')
            sig_label = sig.get('label')
            parent_id = sig.get('parentID')

            # Ignore built-in signatures
            if sig_label in self.builtin_sigs:
                continue
                
            atoms = [atom.get('label') for atom in sig.findall('atom')]
            
            self.signatures[sig_id] = {
                'label': sig_label,
                'atoms': atoms,
                'builtin': sig.get('builtin') == 'yes',
                'parent_id': parent_id,
            }

            # Organize atoms by signature label
            if not self.signatures[sig_id]['builtin']:
                self.atoms_by_sig[sig_label] = atoms
                #print(atoms)
        
        # Parse fields
        for field in self.root.findall('.//field'):
            field_id = field.get('ID')
            field_label = field.get('label')
            parent_id = field.get('parentID')
            
            tuples = []
            for tuple_elem in field.findall('tuple'):
                atoms = [atom.get('label') for atom in tuple_elem.findall('atom')]
                if len(atoms) >= 2:
                    tuples.append((atoms[0], atoms[1]))
            
            self.fields[field_id] = {
                'label': field_label,
                'parent_id': parent_id,
                'tuples': tuples
            }
            #print(self.fields[field_id])


        # =========================================================
        # --- SHOW THE EXTRACTED TREE IN SERVER LOGS ---
        # =========================================================

        # Convert to JSON formatted with 2-space indentation
        #str_tree = json.dumps(full_tree, indent=2, ensure_ascii=False)
        
        #logger.warning("=== STRUCTURE OBTAINED FROM XML ===\n%s\n===================================", str_tree)



    
    def get_class_name(self, sig_label: str) -> str:
        """
        Extracts the class name from a signature label.
        Args:
            sig_label: label of the signature (e.g., 'this/Player')

        Returns:
            Class name (e.g., 'Player')
        """
        if '/' in sig_label:
            return sig_label.split('/')[-1]
        return sig_label
    
    def remove_class_prefix(self, field_name: str, class_name: str) -> str:
        """
        Removes the class prefix from a field name.
        Args:
            field_name: field name (e.g., 'Player_name')
            class_name: class name (e.g., 'Player')

        Returns:
            Field name without prefix (e.g., 'name')
        """
        prefix = f"{class_name}_"
        if field_name.startswith(prefix):
            return field_name[len(prefix):]
        elif field_name.__contains__("_"):
            return field_name[field_name.index("_")+1:]
        return field_name

    def is_enum_value(self, atom_label: str) -> bool:
        """Determines if an atom is an enumeration value."""
        return atom_label.startswith('ENUM_')
    
    def get_enum_value(self, atom_label: str) -> str:
        """
        Extracts the enumeration value from an atom label.
        Args:
            atom_label: atom label (e.g., 'ENUM_Position_CENTER$0')

        Returns:
            Enumeration value (e.g., 'CENTER')
        """
        # Format: ENUM_EnumName_VALUE$n
        parts = atom_label.split('_')
        if len(parts) >= 3:
            value = '_'.join(parts[2:])  # take everything after ENUM_EnumName_
            # Remove suffix $n
            if '$' in value:
                value = value.split('$')[0]
            return value
        return atom_label
    
    def is_primitive_type(self, atom_label: str) -> bool:
        """Determines if an atom represents a primitive type."""
        try:
            int(atom_label)
            return True
        except ValueError:
            pass
        return '$' in atom_label
    
    def get_primitive_value(self, atom_label: str, atom_type: str | None = None) -> any:
        """
        Extracts the primitive value of an atom.
        Args:
            atom_label: atom label
            atom_type: expected type (Int, String, etc.)

        Returns:
            Converted primitive value
        """
        # Integers
        try:
            return int(atom_label)
        except ValueError:
            pass
        
        # Strings - return identifier without suffix
        if '$' in atom_label:
            base_name = atom_label.split('$')[0]
            return f'"{base_name}"'  # Return as quoted string
        
        return f'"{atom_label}"'
    
    DATE_SIG_PATTERN = re.compile(r"^d\d{8}$")
    
    def _date_sig_label(self) -> str | None:
        """Returns the label of the 'date' signature (e.g., 'this/date') if it exists."""
        for sig_label in self.atoms_by_sig:
            if self.get_class_name(sig_label) == "date":
                return sig_label
        return None
    
    def is_date_value(self, atom_label: str) -> bool:
        """
        Determines if an atom represents a date value.

        Recognizes both literals of the form ``dMMDDYYYY`` (as emitted by OCL constraints)
        and free atoms of the ``date`` signature generated by Alloy (e.g., ``date$0``, ``date$01``,
        or other strings).
        """
        base = atom_label.split("$")[0]
        if self.DATE_SIG_PATTERN.match(base):
            return True
        date_sig_label = self._date_sig_label()
        return bool(date_sig_label and atom_label in self.atoms_by_sig[date_sig_label])
    
    def get_date_value(self, atom_label: str) -> str:
        """
        Extracts the date value from an atom.

        Literals of the form ``dMMDDYYYY`` are decoded to 'DD-MM-YYYY'; other atoms of the ``date``
        signature are returned as found by Alloy, enclosed in quotes (e.g., '"date$0"').
        Args:
            atom_label: atom label (e.g., 'd01012000$0' or 'date$01')

        Returns:
            Date value as a string with quotes (e.g., '"01-01-2000"')
        """
        base = atom_label.split("$")[0]
        if self.DATE_SIG_PATTERN.match(base):
            return f'"{base[3:5]}-{base[1:3]}-{base[5:9]}"'
        return f'"{atom_label}"'
    
    def is_domain_class_name(self, class_name: str) -> bool:
        """Determines if *class_name* is a user domain class."""
        if not class_name:
            return False
        if self.is_enum_value(class_name) or class_name.startswith("ENUM_"):
            return False
        if class_name in ("str", "Bool", "True", "False", "date", "Ord"):
            return False
        return not self.DATE_SIG_PATTERN.match(class_name)
    
    def is_object_reference(self, atom_label: str) -> bool:
        """
        Determines if an atom is a reference to another domain object.
        Args:
            atom_label: atom label to check

        Returns:
            True if it is a reference to an object, False if it is primitive
        """
        # Domain objects are represented with format ClassName$N
        # Examples: Player$0, Team$1, City$0, Fan$3
        if '$' in atom_label:
            base = atom_label.split('$')[0]

            # Exclude special types and types that are not domain objects
            if base in ['str', 'pepe', 'Position'] or base.startswith('ENUM_'):
                return False

            # Check if it exists in atoms_by_sig with the prefix this/
            for sig_label in self.atoms_by_sig:
                class_name = self.get_class_name(sig_label)
                if (class_name == base
                        and atom_label in self.atoms_by_sig[sig_label]
                        and class_name not in ['str', 'Bool', 'True', 'False']):
                    return True
        return False
    


    def get_fields_for_signature(self, sig_label: str) -> dict[str, list[tuple]]:
            sig_id = None
            for sid, sig_data in self.signatures.items():
                if sig_data['label'] == sig_label:
                    sig_id = sid
                    break

            if not sig_id:
                return {}

            fields_dict = {}
            for field_data in self.fields.values():
                if field_data['parent_id'] == sig_id:          # ← no else
                    field_name = field_data['label']
                    fields_dict[field_name] = field_data['tuples']

            return fields_dict


    def _pair_association_fields(self) -> dict[str, frozenset]:
        """
        Pairs the two ends of the same bidirectional association.

        The Alloy encoding represents a bidirectional association as two fields with exactly transposed
        sets of tuples. This mapping allows one to deduplicate only those two halves without collapsing
        distinct associations between the same pair of objects.
        """
        field_tuples: dict[str, set[tuple]] = {}
        for field_data in self.fields.values():
            label = field_data['label']
            field_tuples[label] = set(field_data['tuples'])

        used: set[str] = set()
        paired: dict[str, frozenset] = {}
        for field_label, tuples in field_tuples.items():
            if field_label in used or not tuples:
                continue

            transposed = {(to_atom, from_atom) for from_atom, to_atom in tuples}
            partner = None
            for other_label, other_tuples in field_tuples.items():
                if other_label in used or other_label == field_label or not other_tuples:
                    continue
                if other_tuples == transposed:
                    partner = other_label
                    break

            if partner:
                assoc = frozenset([field_label, partner])
                paired[field_label] = assoc
                paired[partner] = assoc
                used.update([field_label, partner])
            else:
                paired[field_label] = frozenset([field_label])

        return paired






    def generate_object_diagram_code(self) -> str:
        """
        Generates BUML code for the object diagram derived from the XML.

        Only the most specific concrete class of each atom is instantiated,
        inherited attributes are incorporated, and multiple associations
        between the same classes or objects are preserved.
        """
        code_lines = []

        # Identify the domain classes. The enumeration signatures should not
        # be materialized as objects.
        domain_classes = set()
        for sig_label, atoms in self.atoms_by_sig.items():
            if not sig_label.startswith("this/"):
                continue
            class_name = self.get_class_name(sig_label)
            if not self.is_domain_class_name(class_name):
                continue
            if atoms and all(self.is_enum_value(atom) for atom in atoms):
                continue
            domain_classes.add(class_name)

        def signature_depth(sig_id: str | None) -> int:
            depth = 0
            current_id = sig_id
            while current_id and current_id in self.signatures:
                parent_id = self.signatures[current_id].get('parent_id')
                if not parent_id or parent_id not in self.signatures:
                    break
                depth += 1
                current_id = parent_id
            return depth

        domain_signatures = []
        for sig_id, sig_data in self.signatures.items():
            class_name = self.get_class_name(sig_data['label'])
            if class_name not in domain_classes:
                continue
            domain_signatures.append({
                'class_name': class_name,
                'atoms': set(sig_data['atoms']),
                'depth': signature_depth(sig_id),
            })

        def leaf_class_for(atom_label: str) -> str | None:
            """Returns the most specific concrete class that contains the atom."""
            containing = [sig for sig in domain_signatures if atom_label in sig['atoms']]
            if not containing:
                return None
            leaf_sig = max(
                containing,
                key=lambda sig: (sig['depth'], -len(sig['atoms']), sig['class_name'])
            )
            return leaf_sig['class_name']

        created_objects = {}  # atom_label -> variable_name
        relations = []  # [(from_var, relation_name, to_atom, field_name), ...]

        for sig_label, atoms in self.atoms_by_sig.items():
            class_name = self.get_class_name(sig_label)

            if class_name not in domain_classes:
                continue

            for i, atom_label in enumerate(atoms):
                if leaf_class_for(atom_label) != class_name:
                    continue

                obj_var = f"{class_name.lower()}_{i}_obj"
                obj_name = atom_label.replace('$', '_')

                created_objects[atom_label] = obj_var
                attributes = {}

                # Traverse all fields to also include attributes and associations
                # inherited from ancestor classes.
                for field_data in self.fields.values():
                    field_name = field_data['label']
                    tuples = field_data['tuples']
                    attr_name = self.remove_class_prefix(field_name, class_name)

                    for tuple_from, tuple_to in tuples:
                        if tuple_from != atom_label:
                            continue

                        if self.is_date_value(tuple_to):
                            attributes[attr_name] = self.get_date_value(tuple_to)
                        elif self.is_object_reference(tuple_to):
                            relations.append((obj_var, attr_name, tuple_to, field_name))
                        elif self.is_enum_value(tuple_to):
                            enum_value = self.get_enum_value(tuple_to)
                            attributes[attr_name] = f'"{enum_value}"'
                        else:
                            attributes[attr_name] = self.get_primitive_value(tuple_to)

                attribute_mapping_parts = []
                for attr_name, attr_value in attributes.items():
                    attribute_mapping_parts.append(f"{attr_name!r}: {attr_value}")

                if attribute_mapping_parts:
                    code_lines.append(
                        f'{obj_var} = {class_name}("{obj_name}").attributes(**{{{", ".join(attribute_mapping_parts)}}}).build()'
                    )
                else:
                    code_lines.append(
                        f'{obj_var} = {class_name}("{obj_name}").build()'
                    )
        
        # add blank line
        code_lines.append("")
        
        # Add comment for relations
        if relations:
            code_lines.append("# Set relations between objects")

        paired_fields = self._pair_association_fields()
        seen_links = set()
        deduplicated_relations = []
        for from_var, relation_name, to_atom, field_name in relations:
            if to_atom not in created_objects:
                continue
            to_var = created_objects[to_atom]
            assoc_id = paired_fields.get(field_name, frozenset([field_name]))
            canonical = (frozenset([from_var, to_var]), assoc_id)
            if canonical in seen_links:
                continue
            seen_links.add(canonical)
            deduplicated_relations.append((from_var, relation_name, to_atom))

        relations = deduplicated_relations

        # Group relations by (from_var, relation_name) to handle multiplicity 'many'
        grouped_relations = {}
        for from_var, relation_name, to_atom in relations:
            if to_atom in created_objects:
                key = (from_var, relation_name)
                if key not in grouped_relations:
                    grouped_relations[key] = []
                grouped_relations[key].append(created_objects[to_atom])
        
        # Generate relations code
        for (from_var, relation_name), to_vars in grouped_relations.items():
            unique_targets = sorted(set(to_vars))
            if len(unique_targets) == 1:
                code_lines.append(
                    f"setattr({from_var}, {relation_name!r}, {unique_targets[0]})"
                )
            else:
                targets_expr = ", ".join(unique_targets)
                code_lines.append(
                    f"setattr({from_var}, {relation_name!r}, {{{targets_expr}}})"
                )
        
        # Add blank line
        if relations:
            code_lines.append("")
        
        # Create ObjectModel
        code_lines.append("# Object Model instance")
        all_objects = ", ".join(created_objects.values())
        code_lines.append("object_model: ObjectModel = ObjectModel(")
        code_lines.append('    name="Object_Diagram",')
        code_lines.append(f"    objects={{{all_objects}}}")
        code_lines.append(")")
        #print()
        #print(code_lines)
        return "\n".join(code_lines)


class BUMLModelIntegrator:
    """Integrates an original BUML model with an object diagram generated from Alloy."""

    def __init__(self, original_buml_file: str, xml_instance_file: str):
        """
        Initializes the integrator.
        Args:
            original_buml_file: Path to the original BUML file (class diagram)
            xml_instance_file: Path to the Alloy instance XML file
        """
        self.original_buml_file = original_buml_file
        self.xml_instance_file = xml_instance_file

        # Read the contents of the original BUML file
        with open(original_buml_file, 'r', encoding='utf-8') as f:
            self.original_content = f.read()
    
    def extract_structural_model_section(self) -> str:
        """
        Extracts the structural model section (class diagram) from the original BUML file.

        Returns:
            The code of the structural model section.
        """
        # Search from beginning until before any object or project section
        patterns = [
            r'################\s*\n#\s*OBJECT MODEL\s*#',
            r'##############\s*\n\s*from besser\.BUML\.metamodel\.object',
            r'######################\s*\n#\s*PROJECT DEFINITION\s*#'
        ]
        
        end_pos = len(self.original_content)
        for pattern in patterns:
            match = re.search(pattern, self.original_content, re.IGNORECASE)
            if match:
                end_pos = min(end_pos, match.start())
        
        structural_section = self.original_content[:end_pos].rstrip()
        return structural_section
    
    def extract_project_section(self) -> str:
        """
        Extracts the project definition section from the original BUML file if it exists.

        Returns:
            The code of the project section or an empty string if not found.
        """
        pattern = r'######################\s*\n#\s*PROJECT DEFINITION\s*#\s*\n######################\s*\n(.*)'
        match = re.search(pattern, self.original_content, re.DOTALL)
        
        if match:
            project_section = match.group(0).strip()

            # Modify the line of models to include object_model
            # Search: models=[domain_model] or models=[domain_model, ...]
            # Replace with: models=[domain_model, object_model]

            # Pattern to find the models line
            models_pattern = r'(models=\[)([^\]]+)(\])'
            
            def replace_models(match):
                prefix = match.group(1)  # "models=["
                models_list = match.group(2).strip()  # current contents
                suffix = match.group(3)  # "]"

                # If already includes object_model, do not modify
                if 'object_model' in models_list:
                    return match.group(0)

                # Add object_model to the list
                if models_list:
                    # There are existing models, append object_model
                    return f"{prefix}{models_list}, object_model{suffix}"
                else:
                    # Empty list, just add object_model
                    return f"{prefix}object_model{suffix}"
            
            project_section = re.sub(models_pattern, replace_models, project_section)
            
            return project_section
        return ""
    
    def generate_integrated_model(self, output_file: str | None = None) -> str:
        """
        Generates the complete integrated BUML model.

        Args:
            output_file: File to save the model (optional)

        Returns:
            The code of the integrated model.
        """
        # 1. Extract structural model (class diagram)
        structural_section = self.extract_structural_model_section()

        # 2. Generate object diagram from Alloy XML
        converter = AlloyToBesserConverter(self.xml_instance_file)
        converter.parse_xml()
        object_diagram_code = converter.generate_object_diagram_code()

        # 3. Extract project section from original BUML
        project_section = self.extract_project_section()

        # 4. Integrate structural section with object model
        integrated_lines = []
        
        # Structural section
        integrated_lines.append(structural_section)
        integrated_lines.append("")
        integrated_lines.append("")
        
        # Objects section
        integrated_lines.append("################")
        integrated_lines.append("# OBJECT MODEL #")
        integrated_lines.append("################")
        integrated_lines.append("")
        integrated_lines.append("from besser.BUML.metamodel.object import ObjectModel")
        integrated_lines.append("import datetime")
        integrated_lines.append("")
        integrated_lines.append(object_diagram_code)
        integrated_lines.append("")
        integrated_lines.append("")

        # Project section (if exists)
        if project_section:
            integrated_lines.append(project_section)
        
        integrated_model = "\n".join(integrated_lines)

        # Save the integrated model to the specified output file if provided
        if output_file:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(integrated_model)
        
        return integrated_model


def main():
    """Main function for usage as a script."""

    if len(sys.argv) < 3:
        print("Usage: python alloy_to_buml_complete.py <original_buml_file> <alloy_xml_file> [output_file]")
        print()
        print("Arguments:")
        print("  original_buml_file : Python file containing the original BUML model (class diagram)")
        print("  alloy_xml_file     : XML file containing instance generated by Alloy Analyzer")
        print("  output_file        : (Optional) File to save the integrated model")
        print()
        print("Example:")
        print("  python alloy_to_buml_complete.py team3.py instance.xml team_integrated.py")
        sys.exit(1)
    
    original_buml_file = sys.argv[1]
    xml_instance_file = sys.argv[2]
    output_file = sys.argv[3] if len(sys.argv) > 3 else None

    # Check that files exist
    if not os.path.exists(original_buml_file):
        print(f"Error: File '{original_buml_file}' does not exist.")
        sys.exit(1)
    
    if not os.path.exists(xml_instance_file):
        print(f"Error: File '{xml_instance_file}' does not exist.")
        sys.exit(1)

    # Create integrator and generate model
    integrator = BUMLModelIntegrator(original_buml_file, xml_instance_file)
    integrator.generate_integrated_model(output_file)

    if output_file:
        print(f"\n✓ BUML model + generated object diagram: {output_file}")
   

if __name__ == "__main__":
    main()
