"""The BESSER version is recorded in generated output (issue #617).

- Web-editor zips carry ``BESSER_GENERATION.md`` (version, generator, options, no secrets).
- Single-file downloads carry a leading version comment where the file type allows one.
- B-UML exports start with ``# Generated by BESSER <version>`` and still load back.
- Spec-Driven runs record the version in the recipe and ship the same provenance file.
"""

import ast
import configparser
import asyncio
import io
import json
import sqlite3
import zipfile
from pathlib import Path

import httpx
import pytest
from httpx._transports.asgi import ASGITransport

from besser.BUML.metamodel.project import Project
from besser.BUML.metamodel.structural import Metadata
from besser.utilities.buml_code_builder import domain_model_to_code
from besser.utilities.buml_code_builder.project_builder import project_to_code
from besser.utilities.provenance import PROVENANCE_FILENAME
from besser.utilities.web_modeling_editor.backend.backend import app
from besser.utilities.web_modeling_editor.backend.routers.generation_router import _streaming_zip
from besser.utilities.web_modeling_editor.backend.services.converters import process_class_diagram
from besser.utilities.web_modeling_editor.backend.services.converters.buml_to_json.class_diagram_converter import (
    parse_buml_content,
)
from besser.utilities.web_modeling_editor.backend.services.converters.buml_to_json.project_converter import (
    project_to_json,
)
from besser.utilities.web_modeling_editor.backend.services.spec_driven.runner import SmartGenerationRunner
from tests.utilities.web_modeling_editor.backend.spec_driven.test_runner import _build_request

_SETUP_CFG = configparser.ConfigParser()
_SETUP_CFG.read(Path(__file__).resolve().parents[2] / "setup.cfg", encoding="utf-8")
VERSION = _SETUP_CFG["metadata"]["version"]
HEADER = f"# Generated by BESSER {VERSION}\n"

CLASS_MODEL = {
    "type": "ClassDiagram",
    "elements": {
        "class-1": {"type": "Class", "name": "Author", "attributes": ["attr-1"], "methods": []},
        "attr-1": {"type": "Attribute", "name": "+ name: str"},
        "class-2": {"type": "Class", "name": "Book", "attributes": ["attr-2"], "methods": []},
        "attr-2": {"type": "Attribute", "name": "+ title: str"},
    },
    "relationships": {
        "rel-1": {
            "type": "ClassBidirectional",
            "source": {"element": "class-1", "multiplicity": "1..*", "role": "authors"},
            "target": {"element": "class-2", "multiplicity": "0..*", "role": "books"},
        },
    },
}


def _post(payload):
    async def _request():
        async with httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://testserver") as client:
            return await client.post("/besser_api/generate-output", json=payload)
    return asyncio.run(_request())


def _generate(generator, config=None):
    response = _post({"title": "Library", "model": CLASS_MODEL, "generator": generator, "config": config})
    assert response.status_code == 200, response.text
    return response


def _zip_entries(content: bytes) -> dict:
    with zipfile.ZipFile(io.BytesIO(content)) as archive:
        return {name: archive.read(name) for name in archive.namelist()}


@pytest.fixture(autouse=True)
def _isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)


def test_api_root_reports_the_besser_version():
    async def _request():
        async with httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://testserver") as client:
            return await client.get("/besser_api/")
    data = asyncio.run(_request()).json()
    assert data["besser_version"] == VERSION


class TestGeneratedZip:
    def test_zip_has_provenance_file_with_version_generator_and_options(self):
        response = _generate("django", {
            "project_name": "library_site", "app_name": "books", "containerization": False,
            "api_key": "sk-NEVER-LEAK-123", "github_token": "ghp_NEVER_LEAK",
        })
        entries = _zip_entries(response.content)
        assert PROVENANCE_FILENAME in entries
        text = entries[PROVENANCE_FILENAME].decode("utf-8")
        assert f"BESSER version: `{VERSION}`" in text
        assert "Generator: `django`" in text
        assert "project_name: `library_site`" in text
        assert "app_name: `books`" in text
        assert "https://github.com/BESSER-PEARL/BESSER" in text
        assert "overwrites" in text
        assert "NEVER" not in text and "api_key" not in text and "token" not in text

    def test_standard_zip_generator_has_provenance_file(self):
        entries = _zip_entries(_generate("java").content)
        assert "Generator: `java`" in entries[PROVENANCE_FILENAME].decode("utf-8")

    def test_two_generations_are_identical_including_the_provenance_file(self):
        first = _zip_entries(_generate("backend").content)
        second = _zip_entries(_generate("backend").content)
        assert PROVENANCE_FILENAME in first
        assert first == second

    def test_provenance_entry_itself_is_byte_identical(self):
        def entry_info(content):
            with zipfile.ZipFile(io.BytesIO(content)) as archive:
                info = archive.getinfo(PROVENANCE_FILENAME)
                return info.date_time, info.CRC, archive.read(PROVENANCE_FILENAME)
        assert entry_info(_generate("java").content) == entry_info(_generate("java").content)

    def test_agent_zip_gets_provenance_file(self):
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w") as archive:
            archive.writestr("agent.py", "print('hi')\n")
        _streaming_zip(buffer, "agent_output.zip")
        entries = _zip_entries(buffer.getvalue())
        assert set(entries) == {"agent.py", PROVENANCE_FILENAME}
        assert "Generator: `agent`" in entries[PROVENANCE_FILENAME].decode("utf-8")


class TestSingleFile:
    def test_python_file_starts_with_version_comment_and_parses(self):
        body = _generate("python").text
        assert body.startswith(HEADER)
        ast.parse(body)

    def test_sql_file_starts_with_version_comment_and_runs(self):
        body = _generate("sql", {"dialect": "sqlite"}).text
        assert body.startswith(f"-- Generated by BESSER {VERSION}\n")
        with sqlite3.connect(":memory:") as connection:
            connection.executescript(body)

    def test_json_file_is_left_unchanged(self):
        body = _generate("jsonschema").text
        assert "Generated by BESSER" not in body
        json.loads(body)


class TestBumlExport:
    def test_domain_model_file_starts_with_version_and_round_trips(self, tmp_path):
        path = tmp_path / "model.py"
        domain_model_to_code(process_class_diagram({"title": "Library", "model": CLASS_MODEL}), str(path))
        code = path.read_text(encoding="utf-8")
        assert code.startswith(HEADER)
        parsed = parse_buml_content(code)
        assert {c.name for c in parsed.get_classes()} == {"Author", "Book"}

    def test_project_file_has_one_version_header_and_round_trips(self, tmp_path):
        domain = process_class_diagram({"title": "Library", "model": CLASS_MODEL})
        path = tmp_path / "project.py"
        project_to_code(Project(
            name="LibraryProject", models=[domain], owner="me", metadata=Metadata(description="d"),
        ), str(path))
        code = path.read_text(encoding="utf-8")
        assert code.startswith(HEADER)
        assert code.count("Generated by BESSER") == 1
        diagrams = project_to_json(code)["diagrams"]["ClassDiagram"]
        names = {e["name"] for e in diagrams[0]["model"]["elements"].values() if e["type"] == "Class"}
        assert names == {"Author", "Book"}


class TestSpecDriven:
    def _package(self, tmp_path, files):
        result_path = tmp_path / "result"
        result_path.mkdir()
        for name, text in files.items():
            (result_path / name).write_text(text, encoding="utf-8")
        (result_path / ".besser_recipe.json").write_text(
            json.dumps({"generator_used": "backend", "llm_model": "claude-sonnet-4-5"}), encoding="utf-8"
        )
        runner = SmartGenerationRunner(_build_request())
        runner.temp_dir = str(tmp_path)
        return result_path, runner._package_result(str(result_path))

    def test_recipe_records_the_besser_version(self, tmp_path):
        result_path, (done, _) = self._package(tmp_path, {"main.py": "x = 1\n", "app.py": "y = 2\n"})
        assert done.recipe["besser_version"] == VERSION
        on_disk = json.loads((result_path / ".besser_recipe.json").read_text(encoding="utf-8"))
        assert on_disk["besser_version"] == VERSION

    def test_zip_download_carries_provenance_file(self, tmp_path):
        _, (done, entry) = self._package(tmp_path, {"main.py": "x = 1\n", "app.py": "y = 2\n"})
        text = _zip_entries(open(entry.file_path, "rb").read())[PROVENANCE_FILENAME].decode("utf-8")
        assert f"BESSER version: `{VERSION}`" in text
        assert "Generator: `spec_driven_agent`" in text
        assert "base_generator: `backend`" in text
        assert "NEVER-LEAK" not in text
        assert done.fileCount == 2

    def test_single_file_run_stays_a_single_file_but_the_workspace_has_provenance(self, tmp_path):
        result_path, (done, entry) = self._package(tmp_path, {"main.py": "x = 1\n"})
        assert entry.is_zip is False and entry.file_name == "main.py"
        # The GitHub push copies the workspace, so the file travels there.
        assert (result_path / PROVENANCE_FILENAME).is_file()


def test_build_sha_is_shown_only_when_the_image_was_stamped(monkeypatch):
    from besser.utilities.provenance import generation_provenance_markdown
    monkeypatch.setenv("BESSER_BUILD_SHA", "unknown")
    assert "BESSER build" not in generation_provenance_markdown("java")
    monkeypatch.setenv("BESSER_BUILD_SHA", "abc1234")
    assert "BESSER build: `abc1234`" in generation_provenance_markdown("java")


def test_provenance_file_is_not_counted_as_an_llm_authored_file(tmp_path):
    from besser.utilities.web_modeling_editor.backend.services.spec_driven.telemetry import compute_file_split
    (tmp_path / "main.py").write_text("x = 1\n", encoding="utf-8")
    (tmp_path / PROVENANCE_FILENAME).write_text("# Generated by BESSER\n", encoding="utf-8")
    split = compute_file_split(str(tmp_path), {"main.py"}, set())
    assert split["total"] == 1 and split["llm_authored"] == 0


def test_modify_seed_drops_the_previous_provenance_file(tmp_path):
    from besser.utilities.web_modeling_editor.backend.services.spec_driven.runner import _seed_workspace_from_base
    base, dest = tmp_path / "base", tmp_path / "dest"
    base.mkdir()
    dest.mkdir()
    (base / "main.py").write_text("x = 1\n", encoding="utf-8")
    (base / PROVENANCE_FILENAME).write_text("# Generated by BESSER 0.0.1\n", encoding="utf-8")
    _seed_workspace_from_base(str(base), str(dest))
    assert (dest / "main.py").is_file()
    assert not (dest / PROVENANCE_FILENAME).exists()
