from antlr4 import InputStream, CommonTokenStream, ParseTreeListener, ParseTreeWalker
from bocl.OCLWrapper import OCLWrapper
from besser.BUML.metamodel.structural import Class, Enumeration
from besser.BUML.notations.ocl.BOCLLexer import BOCLLexer
from besser.BUML.notations.ocl.BOCLParser import BOCLParser
from besser.BUML.notations.ocl.error_handling import BOCLErrorListener, BOCLSyntaxError
import re


def _parse_only(expression: str) -> "BOCLParser.OclFileContext":
    """Run the OCL lexer + parser for syntax validation without evaluating.

    Raises BOCLSyntaxError if the expression is syntactically invalid.
    Returns the ANTLR parse tree so callers can run semantic checks on it.
    """
    input_stream = InputStream(expression)
    lexer = BOCLLexer(input_stream)
    lexer.removeErrorListeners()
    error_listener = BOCLErrorListener()
    lexer.addErrorListener(error_listener)
    stream = CommonTokenStream(lexer)
    parser = BOCLParser(stream)
    parser.removeErrorListeners()
    parser.addErrorListener(error_listener)
    tree = parser.oclFile()
    if error_listener.has_errors():
        raise BOCLSyntaxError(error_listener.errors)
    return tree


class _EnumLiteralCollector(ParseTreeListener):
    """Collects every ``Enumeration::literal`` reference in a parse tree.

    The grammar rule ``ID DOUBLECOLON ID`` (#enumLiteralExpr) accepts any
    identifier pair, so a reference to a non-existent enumeration or literal
    (e.g. ``TCategory::JUNIOR``) parses as syntactically valid. This listener
    walks the tree and records every enum literal reference along with its
    source line so callers can validate it semantically against the model.
    """

    def __init__(self) -> None:
        self.references: list[tuple[str, str, int]] = []

    def enterEnumLiteralExpr(self, ctx):
        ids = ctx.ID()
        if len(ids) >= 2:
            self.references.append(
                (ids[0].getText(), ids[1].getText(), ctx.start.line)
            )


def _validate_enum_literals(domain_model, tree):
    """Semantic check of ``Enumeration::literal`` references in a parse tree.

    Returns a list of warning strings describing enumerations or literals that
    do not exist in ``domain_model``. An empty list means every referenced
    enumeration literal resolves against the model.
    """
    collector = _EnumLiteralCollector()
    ParseTreeWalker.DEFAULT.walk(collector, tree)
    enums = {
        t.name: t for t in domain_model.types if isinstance(t, Enumeration)
    }
    problems = []
    for enum_name, literal_name, line in collector.references:
        enum = enums.get(enum_name)
        if enum is None:
            problems.append(
                f"line {line}: enumeration '{enum_name}' (used in "
                f"'{enum_name}::{literal_name}') does not exist in the model"
            )
        elif literal_name not in {lit.name for lit in enum.literals}:
            problems.append(
                f"line {line}: literal '{enum_name}::{literal_name}' does not "
                f"exist in enumeration '{enum_name}'"
            )
    return problems


def extract_context_class_name(expression):
    """Extract the context class name from an OCL expression"""
    try:
        # Look for pattern: context ClassName
        match = re.search(r'context\s+(\w+)', expression, re.IGNORECASE)
        if match:
            return match.group(1)
        return ""
    except:
        return ""

def is_basic_ocl_syntax_valid(expression):
    """Basic OCL syntax validation without full parsing"""
    try:
        # Check for basic OCL structure
        if not expression.strip():
            return False
        
        # Must start with context
        if not expression.strip().lower().startswith('context'):
            return False
        
        # Check for balanced parentheses
        open_parens = expression.count('(')
        close_parens = expression.count(')')
        if open_parens != close_parens:
            return False
        
        # Check for basic OCL keywords that suggest valid structure
        ocl_keywords = ['inv', 'pre', 'post', 'self', 'collect', 'select', 'exists', 'forall', 'size']
        has_ocl_keywords = any(keyword in expression.lower() for keyword in ocl_keywords)
        
        return has_ocl_keywords
    except:
        return False

def _ensure_canonical_expression(constraint, kind: str, method=None) -> None:
    """In-place upgrade of legacy body-only ``constraint.expression``.

    Constraints loaded from BUML files generated by the *previous*
    ``domain_model_builder`` — before this PR taught it to emit full
    canonical text and ``Method.add_pre`` / ``add_post`` calls — store
    expressions as body-only (``"self.balance >= 0"``). The validator's
    BOCL-based syntax check and the BOCL evaluator both require the
    full ``context X (inv|pre|post) ...:`` form, so we lift body-only
    expressions to canonical here once, mutating ``constraint.expression``
    so every downstream consumer (display, parse, evaluate) sees the
    same full-text shape produced by the JSON-to-BUML pipeline.

    Pre/post need a ``method`` to reconstruct the ``::method(params)``
    segment; if none is provided we fall back to an invariant-shaped
    header rather than emitting a half-broken precondition.
    """
    expr = (constraint.expression or "").lstrip()
    if expr.lower().startswith("context"):
        return
    ctx = getattr(constraint, "context", None)
    ctx_name = getattr(ctx, "name", None) or "?"
    body = constraint.expression
    if kind == "invariant" or method is None:
        constraint.expression = f"context {ctx_name} inv {constraint.name}: {body}"
        return
    params = ", ".join(
        f"{p.name}: {(getattr(getattr(p, 'type', None), 'name', None) or 'any')}"
        for p in (getattr(method, "parameters", None) or [])
    )
    kind_kw = "pre" if kind == "precondition" else "post"
    constraint.expression = (
        f"context {ctx_name}::{method.name}({params}) {kind_kw}: {body}"
    )


def _collect_all_constraints(domain_model):
    """Yield ``(label, kind, constraint)`` for every OCL constraint in the
    model.

    Walks ``domain_model.constraints`` (invariants) + every class's methods'
    ``.pre`` / ``.post`` lists (method contracts). Labels include the
    class / method / kind / name so error messages point at a specific
    constraint box in the editor.

    The displayed expression is ``constraint.expression`` directly: every
    constraint built through the JSON-to-BUML pipeline carries the full
    canonical OCL text on its expression field (set in
    ``ocl_parser.parse_constraint_text``), so no reconstruction is needed
    here.

    ``kind`` is one of ``"invariant"`` / ``"precondition"`` /
    ``"postcondition"`` and is used by the caller to skip evaluation of
    pre/post against an object model — those are runtime contracts that
    bind to method parameters at *invocation* time, which the standalone
    validator has no way to do.
    """
    for c in domain_model.constraints:
        _ensure_canonical_expression(c, "invariant")
        ctx_name = c.context.name if c.context is not None else "?"
        yield (f"[{ctx_name} inv {c.name}]", "invariant", c)
    for cls in domain_model.types:
        if not isinstance(cls, Class):
            continue
        for method in cls.methods:
            for c in method.pre:
                _ensure_canonical_expression(c, "precondition", method)
                yield (f"[{cls.name}::{method.name} pre {c.name}]", "precondition", c)
            for c in method.post:
                _ensure_canonical_expression(c, "postcondition", method)
                yield (f"[{cls.name}::{method.name} post {c.name}]", "postcondition", c)


def check_ocl_constraint(domain_model, object_model = None):
    """
    Check all OCL constraints in the domain model — class invariants plus
    method preconditions and postconditions.
    """
    try:
        constraints = list(_collect_all_constraints(domain_model))
        if not constraints:
            return {
                "success": True,
                "message": "",
                "valid_constraints": [],
                "invalid_constraints": [],
                "warning_constraints": []
            }

        valid_constraints = []
        invalid_constraints = []
        warning_constraints = []
        parser = OCLWrapper(domain_model, object_model)

        for label, kind, constraint in constraints:
            expression = constraint.expression
            description = getattr(constraint, "description", None)
            # Suffix appended to every message so non-technical users see the
            # plain-language reason alongside the raw OCL expression.
            explanation_suffix = f" — {description}" if description else ""
            # Pre/post are runtime contracts — evaluating them requires
            # binding method parameters to actual call arguments, which a
            # standalone validator has no way to do (the BOCL evaluator
            # would raise ``NameError: name 'qty' is not defined``). Limit
            # them to a syntax check regardless of whether an object model
            # is available.
            evaluable = (kind == "invariant") and object_model is not None
            try:
                if not evaluable:
                    # Syntax-only check — re-parse the stored expression.
                    # ``constraint.expression`` is the full canonical OCL
                    # text (set in ``parse_constraint_text``), so we can
                    # feed it directly to the BOCL parser.
                    try:
                        tree = _parse_only(expression)
                        # Semantic check on top of the pure syntax pass: the
                        # grammar accepts any ``Enumeration::literal`` pair, so
                        # references to enums/literals missing from the model
                        # are reported as warnings. A constraint with such
                        # problems is NOT listed as valid.
                        problems = _validate_enum_literals(domain_model, tree)
                        if problems:
                            for problem in problems:
                                warning_constraints.append(
                                    f"⚠️ {label} '{expression}' - {problem}{explanation_suffix}"
                                )
                        else:
                            valid_constraints.append(
                                f"✅ {label} '{expression}'{explanation_suffix}"
                            )
                    except BOCLSyntaxError as syntax_err:
                        invalid_constraints.append(
                            f"❌ {label} '{expression}' - {syntax_err}{explanation_suffix}"
                        )
                else:
                    # Evaluate the invariant against the object model. Skip
                    # if there are no instances of the context class to
                    # evaluate against.
                    context_class_name = (
                        constraint.context.name
                        if getattr(constraint, "context", None) is not None
                        else extract_context_class_name(expression)
                    )
                    context_instances = [
                        obj for obj in object_model.objects
                        if hasattr(obj, 'classifier') and obj.classifier.name.lower() == context_class_name.lower()
                    ]

                    if not context_instances:
                        continue

                    # Skip constraints whose referenced attributes are unset on
                    # the instance(s). In user-profile ("user model") diagrams a
                    # blank criterion (e.g. an empty ``age``) is intentionally
                    # not materialised as a slot, so ``self.age`` has no value to
                    # evaluate. Evaluating anyway builds an expression like
                    # "  >= 0 and  <= 120" and blows up with a Python
                    # ``invalid syntax`` error. An unset attribute means "no
                    # constraint to check", so we skip instead.
                    referenced_attrs = set(re.findall(r'self\.(\w+)', expression))
                    if referenced_attrs:
                        def _has_all_referenced(obj):
                            slot_names = {
                                s.attribute.name for s in getattr(obj, 'slots', [])
                            }
                            return referenced_attrs.issubset(slot_names)

                        if not all(_has_all_referenced(obj) for obj in context_instances):
                            continue

                    result = parser.evaluate(constraint)
                    if result is True:
                        valid_constraints.append(
                            f"✅ {label} '{expression}' - Evaluates to: True{explanation_suffix}"
                        )
                    elif result is False:
                        # Prefer the natural-language description as the primary
                        # violation reason when one is provided.
                        violation_reason = description if description else "Evaluates to False"
                        invalid_constraints.append(
                            f"❌ {label} '{expression}' - Constraint violation: {violation_reason}"
                        )
                    else:
                        valid_constraints.append(
                            f"✅ {label} '{expression}' - Evaluates to: {result}{explanation_suffix}"
                        )
            except Exception as e:
                invalid_constraints.append(
                    f"❌ {label} '{expression}' - Error: {str(e)}{explanation_suffix} \n"
                )

        return {
            "success": len(invalid_constraints) == 0,
            "valid_constraints": valid_constraints,
            "invalid_constraints": invalid_constraints,
            "warning_constraints": warning_constraints,
            "message": f"Found {len(valid_constraints)} valid and {len(invalid_constraints)} invalid constraints"
        }

    except Exception as e:
        return {
            "success": False,
            "message": f"{str(e)}",
            "valid_constraints": [],
            "invalid_constraints": [],
            "warning_constraints": []
        }
