# Generated by BESSER DockerComposeGenerator (v2 A2A swarm) - purpose-built BAF agent.
# role=entry  to_peers=['agent_coder']
import asyncio
import json
import logging
import socket
import threading
import urllib.request

from baf.core.agent import Agent
from baf.core.session import Session
from baf.nlp.llm.llm_openai_api import LLMOpenAI
from baf.nlp.intent_classifier.intent_classifier_configuration import LLMIntentClassifierConfiguration

logging.basicConfig(level=logging.INFO, format='{levelname} - {asctime}: {message}', style='{')

agent = Agent('AgentSupervisor')
agent.load_properties('config.yaml')

reply_llm = LLMOpenAI(agent=agent, name='gpt-4o-mini', parameters={})
agent.set_default_ic_config(LLMIntentClassifierConfiguration(
    llm_name='gpt-4o-mini', parameters={},
    use_intent_descriptions=True, use_training_sentences=True,
    use_entity_descriptions=False, use_entity_synonyms=False))

SYSTEM_PROMPT = "You are AgentSupervisor, the human-facing coordinator of an agent swarm. Delegate the task to your team, then synthesize their results into one concise answer for the user."
# Governance policy for a single-merge owner. The generator turns the authored
# merge policy into a runtime instruction for the owner LLM. If a human
# participant is required, the final decision is deferred to the UI instead.
GOVERNANCE_INSTRUCTION = "merge instruction"
# Human-readable policy facts (no LLM directive) shown at the approval step.
GOVERNANCE_SUMMARY = "policy facts"
# tojson would emit JS-style `true`/`false`; render a Python bool literal instead.
GOVERNANCE_REQUIRES_HUMAN = False
# Merge-path completions (candidate / ballot / synthesis) are decision-bearing, not chat:
# run them at temperature 0 so the same inputs yield the same answer and a ballot reliably
# carries its `BALLOT:` line. Default-temperature peer replies are unaffected (each peer
# runs its own LLM); this only pins the owner's own merge-path predicts.
MERGE_PARAMS = {"temperature": 0}
# Voting governance uses a two-round candidate-selection flow, counted
# deterministically in-container by the baked engine below. PRODUCERS and
# VOTERS are decoupled: round 1 collects one candidate from each producer and
# round 2 collects one ballot from each voter. The owner produces or votes
# in-process only if it is itself a producer or participant.
GOVERNANCE_POLICY_TYPE = "VotingPolicy"
GOVERNANCE_RATIO = 0.5
GOVERNANCE_WEIGHTS = {"agent_coder": 0.8, "agent_supervisor": 0.9}       # {voter_service: confidence}
GOVERNANCE_PRODUCERS = ["agent_coder"] # candidate producers (round 1)
GOVERNANCE_OWNER_PRODUCES = False
GOVERNANCE_OWNER_VOTES = True
GOVERNANCE_UNRESOLVED = [] # participants with no service
GOVERNANCE_SELF = "agent_supervisor"
BALLOT_INSTRUCTION = ("\n\nYou are voting under a governance policy. Review ALL the candidate "
                      "outputs above and choose the single best one. End your reply with exactly "
                      "one line `BALLOT: C<k>` (e.g. `BALLOT: C2`), then one sentence of rationale.")

"""Deterministic governance vote tally for the BAF A2A merge agent.

Self-contained (stdlib only) so the docker_compose generator can bake this module's
SOURCE verbatim into the generated agent.py — the count then runs IN the container
with no besser/ANTLR import. The same functions are unit-tested in BESSER
(tests/generators/agents/test_governance_engine.py), so the baked copy is the tested
copy. The helpers implement candidate-selection voting semantics used by governed
merge agents.
"""
import re

_BALLOT_RE = re.compile(r"BALLOT:\s*(C\d+)", re.IGNORECASE)


def parse_ballot(text, candidate_ids):
    """Return the candidate id a reply voted for, or None (abstain / unparseable).

    Looks for the last `BALLOT: C<k>` line (last wins, so a model that restates the
    instruction then answers is read correctly). Only ids in `candidate_ids` count.
    """
    if not text:
        return None
    hits = [m.group(1).upper() for m in _BALLOT_RE.finditer(text)]
    valid = {c.upper(): c for c in candidate_ids}
    for h in reversed(hits):
        if h in valid:
            return valid[h]
    return None


def tally(policy_type, ratio, candidates, ballots):
    """Count candidate-selection votes deterministically. Returns an audit record.

    candidates: [{"id": "C1", "producer": "agent_x#1"}, ...]
    ballots:    [{"voter","source","vote": "C2"|None,"weight": float}, ...]
                vote == None is an abstain.
    Weighting: VotingPolicy uses each ballot's `weight` (participant confidence);
    Majority/AbsoluteMajority use weight 1 per ballot. Winner = the candidate with the
    greatest (weighted) support; `met_ratio` records whether its share cleared `ratio`.
    AbsoluteMajority ratios over ALL ballots (abstentions in the denominator); the
    others over the ballots that actually voted.
    """
    ids = [c["id"] for c in candidates]
    weighted = policy_type == "VotingPolicy"
    scores = {cid: 0.0 for cid in ids}
    cast, abstain = 0, 0
    for b in ballots:
        v = b.get("vote")
        if v in scores:
            scores[v] += float(b.get("weight", 1.0)) if weighted else 1.0
            cast += 1
        else:
            abstain += 1
    # Denominator for the winning candidate's share (same units as `scores`):
    #   VotingPolicy            → total weight actually cast (confidence-weighted)
    #   AbsoluteMajorityPolicy  → every ballot, abstentions included (the "all eligible" rule)
    #   MajorityPolicy / other  → the ballots that actually voted
    if weighted:
        denom = sum(scores.values())
    elif policy_type == "AbsoluteMajorityPolicy":
        denom = float(cast + abstain)
    else:
        denom = float(cast)
    outcome, top = None, -1.0
    for cid in ids:                       # deterministic: first id wins ties by order
        if scores[cid] > top:
            top, outcome = scores[cid], cid
    share = (top / denom) if denom > 0 else 0.0
    thr = ratio if isinstance(ratio, (int, float)) else 0.5
    return {
        "policy": policy_type,
        "ratio": thr,
        "candidates": [{"id": c["id"], "producer": c.get("producer")} for c in candidates],
        "ballots": [{"voter": b.get("voter"), "source": b.get("source"),
                     "vote": b.get("vote"), "weight": b.get("weight", 1.0)} for b in ballots],
        "scores": scores,
        "cast": cast,
        "abstain": abstain,
        "outcome": outcome,
        "share": round(share, 4),
        "met_ratio": share >= thr,
    }


def _gov_weight(voter):
    base = voter.split('#', 1)[0]   # strip a replica suffix (agent_x#2 -> agent_x)
    w = GOVERNANCE_WEIGHTS.get(base)
    return float(w) if isinstance(w, (int, float)) else 1.0

def _gov_footer(decision):
    _t = ", ".join(f"{k}={v:g}" for k, v in decision["scores"].items())
    _line = ("\n\n— governance —\n"
             f"policy {decision['policy']} (ratio {decision['ratio']}); "
             f"winner {decision['outcome']} (share {decision['share']:g}, "
             f"{'met' if decision['met_ratio'] else 'BELOW'} ratio); "
             f"votes [{_t}]; abstain {decision['abstain']}")
    return _line

def _gov_owner_ballot(session, cand_block, ids):
    # The owner's own ballot must carry a parseable `BALLOT: C<k>` line. At temperature 0
    # one completion is usually enough, but validate the structured output actually
    # appeared and re-prompt once (more emphatic) before recording the owner as an abstain
    # — so a single stray completion can't silently drop the owner's vote.
    _msg = cand_block + BALLOT_INSTRUCTION
    _txt = ""
    for _attempt in range(2):
        _txt = reply_llm.predict(message=_msg, session=session,
                                 system_message=SYSTEM_PROMPT, parameters=MERGE_PARAMS)
        if parse_ballot(_txt, ids) is not None:
            return _txt
        _msg = (cand_block + BALLOT_INSTRUCTION + "\n\nYour previous reply did NOT end with the "
                "required `BALLOT: C<k>` line. Reply again, ending with exactly that line.")
    logging.warning("[governance] owner ballot missing a valid BALLOT line after retry; "
                    "recording the owner as an abstain")
    return _txt

# -- A2A client: fan out to every replica of each downstream peer --
def _peer_replica_urls(service, port=8000):
    # Docker DNS can return one address per running replica. Fall back to the
    # service VIP if only one address resolves.
    try:
        ips = sorted({ai[4][0] for ai in socket.getaddrinfo(service, port, proto=socket.IPPROTO_TCP)})
    except OSError:
        ips = []
    return [f"http://{ip}:{port}" for ip in ips] or [f"http://{service}:{port}"]

def _a2a_call(base_url, agent_id, message, leaf=False):
    _params = {"message": message}
    if leaf:
        _params["leaf"] = True
    body = json.dumps({"jsonrpc": "2.0", "agent_id": agent_id, "method": "handle",
                       "params": _params, "id": 1}).encode()
    req = urllib.request.Request(f"{base_url}/a2a", data=body,
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=120) as r:
        data = json.loads(r.read())
    return (data.get("result") or {}).get("reply", "")

# Per-kind framing: how the requester frames the task for each peer kind, and
# the label its reply folds under. Transport is unchanged (`_a2a_call`); kind
# shapes only the message wording and the reply label. "plain" is pass-through.
_KIND_FRAME = {
    "delegates":    ("Delegated subtask — complete it and return the result:\n{task}", "result"),
    "supervises":   ("Review the following work. Return approval or concrete corrections:\n{task}", "review"),
    "revises":      ("Revise the following so it is correct and complete; return the revised version:\n{task}", "revision"),
    "collaborates": ("Collaborator input — react and contribute:\n{task}", "input"),
    "plain":        ("{task}", "reply"),         # plain channel (no kind=) — pass through
}

async def _fanout(task, only=None, leaf=False):
    # Fire all peer replicas concurrently; exceptions are logged and filtered out. When
    # `only` is a set of service names, restrict the fan-out to those peers (the governed
    # vote uses it to address producers in round 1 and voters in round 2 separately).
    coros, meta = [], []
    if only is None or "agent_coder" in only:
        _frame, _label = _KIND_FRAME["plain"]
        _msg = _frame.format(task=task)
        _urls = _peer_replica_urls("agent_coder")
        for _i, url in enumerate(_urls):
            coros.append(asyncio.to_thread(
                _a2a_call, url, "agent_coder", _msg, leaf=leaf))
            # When a service runs more than one replica, suffix the instance
            # index so merge steps and governance votes can tell the copies
            # apart. Single-replica services keep their plain name.
            _sid = "agent_coder" + (f"#{_i + 1}" if len(_urls) > 1 else "")
            meta.append((_sid, _label))
    results = await asyncio.gather(*coros, return_exceptions=True)
    parts = []
    for (svc, lbl), r in zip(meta, results):
        if isinstance(r, Exception):
            logging.warning("_fanout: peer %s raised %s", svc, r)
        else:
            parts.append((svc, lbl, r))
    return parts

def _run_fanout(task, only=None, leaf=False):
    # Synchronous call sites share the async fan-out helper. When already inside
    # an event loop, run the coroutine in a helper thread to avoid nesting
    # `asyncio.run()`.
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(_fanout(task, only=only, leaf=leaf))

    _box = {"parts": [], "error": None}

    def _worker():
        try:
            _box["parts"] = asyncio.run(_fanout(task, only=only, leaf=leaf))
        except Exception as _exc:
            _box["error"] = _exc

    _thread = threading.Thread(target=_worker, daemon=True)
    _thread.start()
    _thread.join()
    if _box["error"] is not None:
        raise _box["error"]
    return _box["parts"]


# -- Entry (human-facing): websocket UI; work state fans out and synthesizes --
platform = agent.use_websocket_platform(use_ui=True)

greetings = agent.new_state('greetings', initial=True)
work = agent.new_state('work')

def greetings_body(session: Session):
    session.reply("Hi! I\u0027m AgentSupervisor. Give me a task for the team.")
greetings.set_body(greetings_body)
greetings.when_no_intent_matched().go_to(work)

def work_body(session: Session):
    task = session.event.message
    # Governed candidate-selection vote.
    # A human ballot is pending, so this message is the human's choice.
    _pending = session.get("gov_pending")
    if GOVERNANCE_REQUIRES_HUMAN and _pending:
        session.delete("gov_pending")
        _ids = [c["id"] for c in _pending["candidates"]]
        _hb = {"voter": "human", "source": "human",
               "vote": parse_ballot(task, _ids) or parse_ballot("BALLOT: " + task.strip(), _ids),
               "weight": 1.0, "raw": task}
        _ballots = _pending["ballots"] + [_hb]
        _decision = tally(GOVERNANCE_POLICY_TYPE, GOVERNANCE_RATIO, _pending["candidates"], _ballots)
        logging.info("[governance] %s", json.dumps(_decision))
        # Present the winning candidate VERBATIM — it is already a complete answer from a real
        # producer; the deterministic footer is the single source of truth for the tally.
        _win = _pending["cand_text"].get(_decision["outcome"], "")
        session.reply(_win + _gov_footer(_decision))
        return

    # Round 1 — collect one candidate output from each PRODUCER (the BPMN branches that
    # flow into the gateway). The owner contributes a candidate only if it is itself a
    # producer; a pure judge/merge owner produces none ("the task says so").
    parts = _run_fanout(task, only=set(GOVERNANCE_PRODUCERS), leaf=True)   # [(service_id, label, text)]
    candidates, cand_text = [], {}
    for _i, (_svc, _lbl, _txt) in enumerate(parts, start=1):
        cid = f"C{_i}"; candidates.append({"id": cid, "producer": _svc}); cand_text[cid] = _txt
    if GOVERNANCE_OWNER_PRODUCES:
        own = reply_llm.predict(message=task, session=session,
                                system_message=SYSTEM_PROMPT, parameters=MERGE_PARAMS)
        _own_id = f"C{len(candidates) + 1}"
        candidates.append({"id": _own_id, "producer": GOVERNANCE_SELF or "self"}); cand_text[_own_id] = own
    if not candidates:
        # Every producer branch failed at runtime (peer down / call raised) — there is nothing
        # to vote on. Degrade gracefully instead of tallying an empty slate and presenting "".
        session.reply("No candidate outputs were produced for the governed merge, so there is "
                      "nothing to vote on. Please retry.")
        return
    _ids = [c["id"] for c in candidates]
    cand_block = "\n\n".join(f"[{c['id']}] (from {c['producer']})\n{cand_text[c['id']]}" for c in candidates)

    # Round 2 — each VOTER (the policy participant list) votes over the FULL candidate set;
    # the owner votes in-process only if it is itself a participant.
    _voters = set(GOVERNANCE_WEIGHTS) - {GOVERNANCE_SELF}
    ballots = []
    for _svc, _lbl, _reply in _run_fanout(cand_block + BALLOT_INSTRUCTION, only=_voters, leaf=True):
        ballots.append({"voter": _svc, "source": "agent", "vote": parse_ballot(_reply, _ids),
                        "weight": _gov_weight(_svc), "raw": _reply})
    if GOVERNANCE_OWNER_VOTES:
        _own_vote = _gov_owner_ballot(session, cand_block, _ids)
        ballots.append({"voter": GOVERNANCE_SELF or "self", "source": "owner",
                        "vote": parse_ballot(_own_vote, _ids), "weight": _gov_weight(GOVERNANCE_SELF or ""),
                        "raw": _own_vote})
    for _name in GOVERNANCE_UNRESOLVED:             # participants with no running service
        ballots.append({"voter": _name, "source": "agent", "vote": None, "weight": 1.0, "raw": ""})

    if GOVERNANCE_REQUIRES_HUMAN:
        # Defer the final tally to the human: stash candidates + the agent/owner ballots,
        # present the slate, and let phase 2 (above) add the human ballot and tally.
        session.set("gov_pending", {"candidates": candidates, "cand_text": cand_text, "ballots": ballots})
        session.reply("A governance policy requires human approval before merging.\n\n"
                      + GOVERNANCE_SUMMARY + "\n\nCandidate outputs:\n" + cand_block
                      + "\n\nReply with the ID you choose (e.g. C2).")
        return

    _decision = tally(GOVERNANCE_POLICY_TYPE, GOVERNANCE_RATIO, candidates, ballots)
    logging.info("[governance] %s", json.dumps(_decision))
    # Present the winning candidate VERBATIM — it is already a complete answer from a real
    # producer; re-running it through the LLM only risks mutating it and re-narrating a fake
    # process. The deterministic footer is the single source of truth for the tally.
    _win = cand_text.get(_decision["outcome"]) or next(iter(cand_text.values()), "")
    final = _win + _gov_footer(_decision)
    session.reply(final)
work.set_body(work_body)
work.when_no_intent_matched().go_to(work)

if __name__ == '__main__':
    agent.run()