"""
GitHub Deployment API - Deploy generated apps to user's GitHub account.

This endpoint generates a web app and pushes it to a GitHub repository
in the user's account, enabling one-click deployment to platforms like Render.
"""

import io
import os
import uuid
import zipfile
import tempfile
import shutil
from typing import Optional
from datetime import datetime

from fastapi import APIRouter, HTTPException, Request, Body, Header
from pydantic import BaseModel, Field

from besser.utilities.web_modeling_editor.backend.services.deployment.github_service import (
    create_github_service
)
from besser.utilities.web_modeling_editor.backend.services.deployment.github_oauth import (
    get_user_token
)
from besser.utilities.web_modeling_editor.backend.services.converters import (
    process_class_diagram,
    process_gui_diagram,
    process_agent_diagram,
)
from besser.utilities.web_modeling_editor.backend.config import get_generator_info


# Create router
router = APIRouter(prefix="/github", tags=["GitHub Deployment"])


class DeployToGitHubRequest(BaseModel):
    """Request model for GitHub deployment."""
    repo_name: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Repository name (alphanumeric, hyphens, underscores)"
    )
    description: Optional[str] = Field(
        None,
        max_length=350,
        description="Repository description"
    )
    is_private: bool = Field(
        default=False,
        description="Make repository private"
    )


class DeployToGitHubResponse(BaseModel):
    """Response model for GitHub deployment."""
    success: bool
    repo_url: str
    repo_name: str
    owner: str
    deployment_urls: dict
    files_uploaded: int
    message: str


@router.post("/deploy-webapp", response_model=DeployToGitHubResponse)
async def deploy_webapp_to_github(
    request: Request,
    body: dict = Body(...),
    github_session: Optional[str] = Header(None, alias="X-GitHub-Session")
):
    """
    Deploy generated web application to user's GitHub repository.
    
    Flow:
    1. Verify user has authenticated with GitHub
    2. Generate web app from project diagrams
    3. Create repository in user's GitHub account
    4. Push generated code to repository
    5. Return repository URL and deployment links
    
    The user can then deploy to Render with one click.
    """
    temp_dir = None
    
    try:
        # Verify GitHub authentication
        if not github_session:
            raise HTTPException(
                status_code=401,
                detail="GitHub authentication required. Please sign in with GitHub first."
            )
        
        access_token = get_user_token(github_session)
        if not access_token:
            raise HTTPException(
                status_code=401,
                detail="GitHub session expired. Please sign in again."
            )
        
        # Create GitHub service
        github = create_github_service(access_token)
        
        # Get authenticated user info
        user_info = github.get_authenticated_user()
        username = user_info.get("login")
        
        # Extract deploy config
        deploy_config = body.get("deploy_config", {})
        repo_name = deploy_config.get("repo_name", "besser-webapp")
        description = deploy_config.get("description", "Web application generated by BESSER")
        is_private = deploy_config.get("is_private", False)
        
        # Sanitize repo name
        repo_name = _sanitize_repo_name(repo_name)
        
        # Extract diagrams
        diagrams = body.get("diagrams", {})
        class_diagram_data = diagrams.get("ClassDiagram", {})
        gui_diagram_data = diagrams.get("GUINoCodeDiagram", {})
        
        if not class_diagram_data or not class_diagram_data.get("model"):
            raise HTTPException(
                status_code=400,
                detail="ClassDiagram is required for web app deployment"
            )
        
        if not gui_diagram_data or not gui_diagram_data.get("model"):
            raise HTTPException(
                status_code=400,
                detail="GUINoCodeDiagram is required for web app deployment"
            )
        
        # Process diagrams to BUML
        buml_model = process_class_diagram(class_diagram_data)
        gui_model = process_gui_diagram(
            gui_diagram_data.get("model"),
            class_diagram_data.get("model"),
            buml_model
        )
        
        # Check for agent diagram
        agent_model = None
        agent_diagram_data = diagrams.get("AgentDiagram", {})
        if agent_diagram_data and agent_diagram_data.get("model"):
            agent_model = process_agent_diagram(agent_diagram_data)
        
        # Generate web app
        temp_dir = tempfile.mkdtemp(prefix=f"besser_github_{uuid.uuid4().hex}_")
        
        generator_info = get_generator_info("web_app")
        generator_class = generator_info.generator_class
        generator = generator_class(
            buml_model,
            gui_model,
            output_dir=temp_dir,
            agent_model=agent_model
        )
        generator.generate()
        
        # Add deployment configuration files
        _add_deployment_configs(temp_dir, repo_name)
        
        # Create GitHub repository
        repo_info = github.create_repository(
            repo_name=repo_name,
            description=description,
            is_private=is_private
        )
        
        repo_full_name = repo_info.get("full_name")
        repo_url = repo_info.get("html_url")
        
        # Push code to repository
        push_results = github.push_directory_to_repo(
            owner=username,
            repo_name=repo_name,
            directory_path=temp_dir,
            commit_message="Initial commit - Generated by BESSER Web Editor"
        )
        
        # Create README with deployment instructions
        github.create_readme(
            owner=username,
            repo_name=repo_name,
            app_name=body.get("name", repo_name),
            deploy_instructions=True
        )
        
        # Get deployment URLs
        deployment_urls = github.get_deployment_urls(username, repo_name)
        
        return DeployToGitHubResponse(
            success=True,
            repo_url=repo_url,
            repo_name=repo_name,
            owner=username,
            deployment_urls=deployment_urls,
            files_uploaded=len(push_results["uploaded_files"]) + 1,  # +1 for README
            message=f"Successfully created repository and pushed {len(push_results['uploaded_files'])} files"
        )
        
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to deploy to GitHub: {str(e)}"
        )
    finally:
        if temp_dir and os.path.exists(temp_dir):
            shutil.rmtree(temp_dir, ignore_errors=True)


def _sanitize_repo_name(name: str) -> str:
    """
    Sanitize repository name to meet GitHub requirements.
    
    - Lowercase
    - Replace spaces with hyphens
    - Remove special characters
    - Max 100 characters
    """
    # Convert to lowercase
    name = name.lower()
    
    # Replace spaces with hyphens
    name = name.replace(" ", "-")
    
    # Remove special characters (keep only alphanumeric, hyphens, underscores)
    name = "".join(c for c in name if c.isalnum() or c in "-_")
    
    # Remove leading/trailing hyphens
    name = name.strip("-_")
    
    # Limit length
    name = name[:100]
    
    # Ensure not empty
    if not name:
        name = f"besser-app-{uuid.uuid4().hex[:8]}"
    
    return name


def _add_deployment_configs(directory: str, app_name: str):
    """
    Add Render deployment configuration (only free platform for full-stack auto-deploy).
    
    Args:
        directory: Path to generated app directory
        app_name: Application name
    """
    # Render configuration - Full stack (backend + frontend) FREE with one click!
    render_config = f"""services:
  # Backend API (Free tier - 750 hours/month, spins down after 15 min idle)
  - type: web
    name: {app_name}-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8000

  # Frontend (Free static site)
  - type: web
    name: {app_name}-frontend  
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
"""
    
    render_path = os.path.join(directory, "render.yaml")
    with open(render_path, "w") as f:
        f.write(render_config)
    
    # Create .env.production for frontend with backend URL
    env_production = f"""# Production environment variables
# Backend API URL - Update this with your deployed backend URL
REACT_APP_API_URL=https://{app_name}-backend.onrender.com

# For Fly.io backend, use: https://{app_name}-backend.fly.dev
# For local development, use: http://localhost:8000
"""
    
    env_prod_path = os.path.join(directory, "frontend", ".env.production")
    with open(env_prod_path, "w") as f:
        f.write(env_production)
    
    # Create .env for local development
    env_local = """# Local development environment variables
REACT_APP_API_URL=http://localhost:8000
"""
    
    env_local_path = os.path.join(directory, "frontend", ".env")
    with open(env_local_path, "w") as f:
        f.write(env_local)
