// ============================================================
//  MapBlock.tsx — generated by BESSER WebAppGenerator
//
//  This file is meant to be EDITED AFTER GENERATION.
//  Each layer type has a clearly labelled section (===== SECTION =====)
//  so you can jump directly to the renderer you need to customise.
//
//  Quick reference:
//    • POINTS LAYER    → Marker + Popup (lines ≈80)
//    • GEOJSON LAYER   → react-leaflet GeoJSON polygons / lines (lines ≈130)
//    • CHOROPLETH LAYER→ GeoJSON with colour-scale + legend (lines ≈180)
//    • HEATMAP LAYER   → leaflet.heat intensity map (lines ≈240)
//    • CUSTOM ICONS / IMAGE POPUPS → commented-out extension section (lines ≈300)
//
//  Column contracts per layer type:
//    points     : latitude (float), longitude (float), [label (any)]
//    geojson    : geometry (GeoJSON string), [label (any)]
//    choropleth : geometry (GeoJSON string), value (float), [label (any)]
//    heatmap    : latitude (float), longitude (float), [weight (0-1)]
// ============================================================

import React, { useEffect, useState } from "react";
import {
  MapContainer,
  TileLayer,
  Marker,
  Popup,
  GeoJSON,
  useMap,
} from "react-leaflet";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import axios from "axios";

// ── Leaflet default-icon fix (required for CRA / Vite bundling) ──────────────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
delete (L.Icon.Default.prototype as any)._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl:
    "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
  iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
  shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
});

// ── Types ─────────────────────────────────────────────────────────────────────
interface DataBindingConfig {
  entity?: string;
  endpoint?: string;
  label_field?: string;
  data_field?: string;
}

interface LayerConfig {
  name?: string;
  /** One of: "points" | "geojson" | "choropleth" | "heatmap" */
  type: string;
  dataBinding?: DataBindingConfig;
  latitudeField?: string;
  longitudeField?: string;
  labelField?: string;
  weightField?: string;
  geojsonField?: string;
  valueField?: string;
}

interface MapConfig {
  centerLatitude?: number;
  centerLongitude?: number;
  zoom?: number;
}

interface MapBlockProps {
  id?: string;
  title?: string;
  mapConfig?: MapConfig;
  /** Multi-layer config array — each layer binds its own DB table / endpoint. */
  layers?: LayerConfig[];
  styles?: React.CSSProperties;
}

// ── Fetch helper (shared normaliser — matches TableBlock.tsx) ─────────────────
const BACKEND = import.meta.env.VITE_API_URL ?? "http://localhost:8000";

/** Fetches rows from a REST endpoint and normalises the response to an array. */
async function fetchRows(endpoint: string): Promise<Record<string, unknown>[]> {
  const url = endpoint.startsWith("/") ? BACKEND + endpoint : endpoint;
  const res = await axios.get<unknown>(url);
  const data = res.data;
  if (Array.isArray(data)) return data as Record<string, unknown>[];
  if (data && typeof data === "object") {
    for (const key of ["data", "results", "items", "records", "list"]) {
      const candidate = (data as Record<string, unknown>)[key];
      if (Array.isArray(candidate)) return candidate as Record<string, unknown>[];
    }
    const firstArray = Object.values(data as Record<string, unknown>).find(
      Array.isArray
    );
    if (firstArray) return firstArray as Record<string, unknown>[];
  }
  return [];
}

// ── Choropleth colour scale (sequential: white → dark-red) ───────────────────
function choroplethColor(value: number, min: number, max: number): string {
  const t = max === min ? 0 : (value - min) / (max - min);
  // 5-step sequential scale (white → red)
  const stops = ["#FFEDA0", "#FED976", "#FEB24C", "#FC4E2A", "#800026"];
  const idx = Math.min(Math.floor(t * stops.length), stops.length - 1);
  return stops[idx];
}

// ────────────────────────────────────────────────────────────────────────────
//  Per-layer renderers
// ────────────────────────────────────────────────────────────────────────────

// ===== POINTS LAYER ==========================================================
// Renders each DB row as a Leaflet Marker.  Required columns: latitude, longitude.
// Optional: any column for the popup label (labelField).
//
// To customise markers:
//   - Custom icon:   replace `<Marker …>` with `<Marker icon={myIcon} …>`
//                    See the "CUSTOM ICONS" extension block at the bottom of this file.
//   - Rich popups:   replace `<Popup>{String(label)}</Popup>` with any JSX.
// =============================================================================
function PointsLayer({ layer }: { layer: LayerConfig }) {
  const [rows, setRows] = useState<Record<string, unknown>[]>([]);
  const latF = layer.latitudeField;
  const lngF = layer.longitudeField;
  const lblF = layer.labelField;
  const endpoint = layer.dataBinding?.endpoint;

  useEffect(() => {
    if (!endpoint || !latF || !lngF) return;
    fetchRows(endpoint)
      .then(setRows)
      .catch((err) => console.warn(`[MapBlock] ${layer.name} fetch error:`, err));
  }, [endpoint, latF, lngF]);

  return (
    <>
      {rows.map((row, idx) => {
        const lat = parseFloat(String(row[latF!]));
        const lng = parseFloat(String(row[lngF!]));
        if (isNaN(lat) || isNaN(lng)) return null;
        const label = lblF ? row[lblF] : undefined;
        return (
          <Marker key={idx} position={[lat, lng]}>
            {label !== undefined && (
              <Popup>{String(label)}</Popup>
            )}
          </Marker>
        );
      })}
    </>
  );
}

// ===== GEOJSON LAYER =========================================================
// Renders a GeoJSON column (geometry) as polygons / lines / points on the map.
// Required columns: geometry (string — a valid GeoJSON FeatureCollection or Feature).
// Optional: labelField for click popups.
//
// To customise polygon style:
//   Modify the `style` prop on <GeoJSON> below.
//   See: https://leafletjs.com/reference.html#geojson-style
// =============================================================================
function GeoJsonLayer({ layer }: { layer: LayerConfig }) {
  const [geoData, setGeoData] = useState<unknown[]>([]);
  const geojsonF = layer.geojsonField;
  const lblF = layer.labelField;
  const endpoint = layer.dataBinding?.endpoint;

  useEffect(() => {
    if (!endpoint || !geojsonF) return;
    fetchRows(endpoint)
      .then((rows) => {
        const parsed: unknown[] = [];
        for (const row of rows) {
          try {
            const raw = row[geojsonF!];
            parsed.push(typeof raw === "string" ? JSON.parse(raw) : raw);
          } catch {
            console.warn(`[MapBlock] ${layer.name}: could not parse geometry row`);
          }
        }
        setGeoData(parsed);
      })
      .catch((err) => console.warn(`[MapBlock] ${layer.name} fetch error:`, err));
  }, [endpoint, geojsonF]);

  return (
    <>
      {geoData.map((feature, idx) => (
        <GeoJSON
          key={idx}
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data={feature as any}
          onEachFeature={
            lblF
              ? (feature, leafletLayer) => {
                  const label = feature?.properties?.[lblF];
                  if (label != null) leafletLayer.bindPopup(String(label));
                }
              : undefined
          }
        />
      ))}
    </>
  );
}

// ===== CHOROPLETH LAYER ======================================================
// Colours GeoJSON polygons by a numeric `value` column using a sequential scale.
// Required columns: geometry (GeoJSON string), value (float).
// Optional: labelField for click popups.
//
// Graceful degradation: if no valueField is set, falls back to a plain GeoJSON
// render with a console warning (never crashes).
//
// To customise the colour scale:
//   Modify `choroplethColor()` above or replace it with a d3-scale call.
// To add a legend:
//   Uncomment the <ChoroplethLegend> component or write your own.
// =============================================================================
function ChoroplethLayer({ layer }: { layer: LayerConfig }) {
  type GeoRow = { feature: unknown; value: number };
  const [rows, setRows] = useState<GeoRow[]>([]);
  const [minVal, setMinVal] = useState(0);
  const [maxVal, setMaxVal] = useState(1);
  const geojsonF = layer.geojsonField;
  const valueF = layer.valueField;
  const lblF = layer.labelField;
  const endpoint = layer.dataBinding?.endpoint;

  if (!valueF) {
    console.warn(
      `[MapBlock] ${layer.name}: choropleth layer has no valueField — falling back to plain GeoJSON`
    );
  }

  useEffect(() => {
    if (!endpoint || !geojsonF) return;
    fetchRows(endpoint)
      .then((rawRows) => {
        const parsed: GeoRow[] = [];
        let mn = Infinity,
          mx = -Infinity;
        for (const row of rawRows) {
          try {
            const raw = row[geojsonF!];
            const feature = typeof raw === "string" ? JSON.parse(raw) : raw;
            const val = valueF ? parseFloat(String(row[valueF])) : 0;
            if (!isNaN(val)) {
              mn = Math.min(mn, val);
              mx = Math.max(mx, val);
            }
            parsed.push({ feature, value: isNaN(val) ? 0 : val });
          } catch {
            console.warn(`[MapBlock] ${layer.name}: could not parse geometry row`);
          }
        }
        setRows(parsed);
        setMinVal(mn === Infinity ? 0 : mn);
        setMaxVal(mx === -Infinity ? 1 : mx);
      })
      .catch((err) => console.warn(`[MapBlock] ${layer.name} fetch error:`, err));
  }, [endpoint, geojsonF, valueF]);

  return (
    <>
      {rows.map(({ feature, value }, idx) => (
        <GeoJSON
          key={idx}
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data={feature as any}
          style={() => ({
            fillColor: valueF
              ? choroplethColor(value, minVal, maxVal)
              : "#3388ff",
            weight: 1,
            opacity: 1,
            color: "#666",
            fillOpacity: 0.7,
          })}
          onEachFeature={(feat, leafletLayer) => {
            const parts: string[] = [];
            if (lblF && feat?.properties?.[lblF] != null)
              parts.push(String(feat.properties[lblF]));
            if (valueF) parts.push(`Value: ${value}`);
            if (parts.length) leafletLayer.bindPopup(parts.join("<br/>"));
          }}
        />
      ))}
      {/* ── Simple choropleth legend ─────────────────────────────────────── */}
      {valueF && rows.length > 0 && (
        <ChoroplethLegend min={minVal} max={maxVal} name={layer.name ?? ""} />
      )}
    </>
  );
}

/** Small Leaflet control legend rendered via a React portal into the map container. */
function ChoroplethLegend({
  min,
  max,
  name,
}: {
  min: number;
  max: number;
  name: string;
}) {
  // Inject legend as a non-blocking overlay div into the map container
  const map = useMap();
  useEffect(() => {
    const legend = L.control({ position: "bottomright" });
    legend.onAdd = () => {
      const div = L.DomUtil.create("div", "leaflet-control-choropleth-legend");
      div.style.cssText =
        "background:white;padding:8px 12px;border-radius:4px;" +
        "box-shadow:0 1px 4px rgba(0,0,0,.3);font-size:12px;line-height:1.6;";
      const stops = ["#FFEDA0", "#FED976", "#FEB24C", "#FC4E2A", "#800026"];
      const step = (max - min) / (stops.length - 1);
      div.innerHTML =
        `<strong style="display:block;margin-bottom:4px">${name}</strong>` +
        stops
          .map((c, i) => {
            const v = (min + step * i).toFixed(1);
            return (
              `<span style="display:inline-block;width:14px;height:14px;` +
              `background:${c};margin-right:4px;vertical-align:middle;` +
              `border:1px solid #999"></span>${v}`
            );
          })
          .join("&nbsp;&nbsp;");
      return div;
    };
    legend.addTo(map);
    return () => {
      legend.remove();
    };
  }, [map, min, max, name]);
  return null;
}

// ===== HEATMAP LAYER =========================================================
// Renders intensity data as a smooth heatmap using leaflet.heat.
// Required columns: latitude (float), longitude (float).
// Optional: weight (0-1 float, defaults to 0.5 if absent).
//
// To adjust heatmap appearance:
//   Modify the options passed to L.heatLayer() below:
//   radius, blur, maxZoom, max, gradient.
//   See: https://github.com/Leaflet/Leaflet.heat#reference
// =============================================================================
function HeatLayer({ layer }: { layer: LayerConfig }) {
  // leaflet.heat is loaded as a side-effect import — no TypeScript types available
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [heatLayerRef, setHeatLayerRef] = useState<any>(null);
  const map = useMap();
  const latF = layer.latitudeField;
  const lngF = layer.longitudeField;
  const wgtF = layer.weightField;
  const endpoint = layer.dataBinding?.endpoint;

  useEffect(() => {
    // Dynamic import of leaflet.heat (it registers itself on L)
    import("leaflet.heat").catch(() => {
      console.warn("[MapBlock] leaflet.heat not installed — run: npm install leaflet.heat");
    });
  }, []);

  useEffect(() => {
    if (!endpoint || !latF || !lngF) return;
    fetchRows(endpoint)
      .then((rows) => {
        const points: [number, number, number][] = [];
        for (const row of rows) {
          const lat = parseFloat(String(row[latF!]));
          const lng = parseFloat(String(row[lngF!]));
          if (isNaN(lat) || isNaN(lng)) continue;
          const weight = wgtF
            ? parseFloat(String(row[wgtF])) || 0.5
            : 0.5;
          points.push([lat, lng, weight]);
        }
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const L_ = L as any;
        if (typeof L_.heatLayer !== "function") {
          console.warn("[MapBlock] L.heatLayer not available — is leaflet.heat installed?");
          return;
        }
        // Remove previous heatmap layer if re-rendered
        if (heatLayerRef) map.removeLayer(heatLayerRef);
        const hl = L_.heatLayer(points, {
          radius: 25,
          blur: 15,
          maxZoom: 17,
        }).addTo(map);
        setHeatLayerRef(hl);
      })
      .catch((err) => console.warn(`[MapBlock] ${layer.name} fetch error:`, err));

    return () => {
      if (heatLayerRef) map.removeLayer(heatLayerRef);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [endpoint, latF, lngF, wgtF, map]);

  return null; // leaflet.heat injects directly into the map — no JSX needed
}

// ────────────────────────────────────────────────────────────────────────────
//  Layer dispatcher — picks the right renderer for each layer
// ────────────────────────────────────────────────────────────────────────────
function LayerRenderer({ layer }: { layer: LayerConfig }) {
  try {
    switch (layer.type) {
      case "points":
        return <PointsLayer layer={layer} />;
      case "geojson":
        return <GeoJsonLayer layer={layer} />;
      case "choropleth":
        return <ChoroplethLayer layer={layer} />;
      case "heatmap":
        return <HeatLayer layer={layer} />;
      default:
        // Unknown / unset type: fall back to points
        console.warn(
          `[MapBlock] Unknown layer type "${layer.type}" for layer "${layer.name}" — falling back to points`
        );
        return <PointsLayer layer={layer} />;
    }
  } catch (err) {
    console.warn(`[MapBlock] Error rendering layer "${layer.name}":`, err);
    return null;
  }
}

// ────────────────────────────────────────────────────────────────────────────
//  MapBlock — public component exported and consumed by generated pages
// ────────────────────────────────────────────────────────────────────────────
export function MapBlock({ id, title, mapConfig, layers = [], styles }: MapBlockProps) {
  const center: [number, number] = [
    mapConfig?.centerLatitude ?? 0,
    mapConfig?.centerLongitude ?? 0,
  ];
  const zoom = mapConfig?.zoom ?? 10;

  const containerStyle: React.CSSProperties = {
    height: "450px",
    width: "100%",
    ...styles,
  };

  return (
    <div id={id}>
      {title && (
        <h3 style={{ marginBottom: "8px", fontWeight: 600 }}>{title}</h3>
      )}
      <MapContainer
        center={center}
        zoom={zoom}
        style={containerStyle}
        scrollWheelZoom={true}
      >
        {/* OpenStreetMap tile layer — no API key required */}
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />

        {/* Render each data layer in order (bottom → top) */}
        {layers.map((layer, idx) => (
          <LayerRenderer key={layer.name ?? idx} layer={layer} />
        ))}

        {/* Static fallback marker when no layers are defined */}
        {layers.length === 0 && (
          <Marker position={center}>
            <Popup>Map centre</Popup>
          </Marker>
        )}
      </MapContainer>
    </div>
  );
}

// ============================================================
//  ===== EXTENSION: CUSTOM MARKER ICONS / IMAGE POPUPS =====
//
//  Uncomment and adapt the blocks below to use custom icons or
//  embed images / HTML in popups.  No metamodel changes required.
//
//  ── Custom Leaflet icon ──────────────────────────────────────
//
//  import customIconPng from "../assets/pin.png";   // add your image
//
//  const myIcon = L.icon({
//    iconUrl: customIconPng,
//    iconSize: [32, 32],      // [width, height] in pixels
//    iconAnchor: [16, 32],    // point on the icon that corresponds to the marker position
//    popupAnchor: [0, -32],   // where the popup opens relative to the icon
//  });
//
//  Then inside PointsLayer, replace:
//    <Marker key={idx} position={[lat, lng]}>
//  with:
//    <Marker key={idx} position={[lat, lng]} icon={myIcon}>
//
//  ── Image popup ──────────────────────────────────────────────
//
//  // Assuming your DB table has an "image_url" column:
//  const imgUrl = String(row["image_url"] ?? "");
//  return (
//    <Marker key={idx} position={[lat, lng]}>
//      <Popup>
//        <div>
//          {imgUrl && <img src={imgUrl} alt="marker" style={{ maxWidth: 180 }} />}
//          <p>{String(label)}</p>
//        </div>
//      </Popup>
//    </Marker>
//  );
//
//  ── Per-layer colour override (points layer) ─────────────────
//
//  const coloredIcon = (color: string) =>
//    L.divIcon({
//      className: "",
//      html: `<span style="font-size:24px;color:${color}">📍</span>`,
//    });
//
//  <Marker icon={coloredIcon("#e74c3c")} position={[lat, lng]}>
// ============================================================
