// ============================================================
//  MapBlock.tsx — generated by BESSER WebAppGenerator
//
//  This file is meant to be EDITED AFTER GENERATION.
//  Each layer type has a clearly labelled section (===== SECTION =====)
//  so you can jump directly to the renderer you need to customise.
//
//  Implementation note: this component drives Leaflet directly (no
//  react-leaflet wrapper) — the map instance lives in a ref, layers are
//  plain Leaflet layer groups, and popup text is always HTML-escaped.
//
//  Quick reference:
//    • POINTS LAYER    → L.marker + popup            (renderPointsLayer)
//    • GEOJSON LAYER   → L.geoJSON polygons / lines  (renderGeoJsonLayer)
//    • CHOROPLETH LAYER→ L.geoJSON + colour scale    (renderChoroplethLayer)
//    • HEATMAP LAYER   → leaflet.heat intensity map  (renderHeatLayer)
//    • CUSTOM ICONS / IMAGE POPUPS → commented-out extension section (bottom)
//
//  Column contracts per layer type:
//    points     : latitude (float), longitude (float), [label (any)]
//    geojson    : geometry (GeoJSON string), [label (any)]
//    choropleth : geometry (GeoJSON string), value (float), [label (any)]
//    heatmap    : latitude (float), longitude (float), [weight (0-1)]
// ============================================================

import React, { useEffect, useRef } from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import axios from "axios";

// ── Types ─────────────────────────────────────────────────────────────────────
interface DataBindingConfig {
  entity?: string;
  endpoint?: string;
  label_field?: string;
  data_field?: string;
}

interface LayerConfig {
  name?: string;
  /** One of: "points" | "geojson" | "choropleth" | "heatmap" */
  type: string;
  dataBinding?: DataBindingConfig;
  latitudeField?: string;
  longitudeField?: string;
  labelField?: string;
  weightField?: string;
  geojsonField?: string;
  valueField?: string;
}

interface MapConfig {
  centerLatitude?: number;
  centerLongitude?: number;
  zoom?: number;
}

interface MapBlockProps {
  id?: string;
  title?: string;
  mapConfig?: MapConfig;
  /** Multi-layer config array — each layer binds its own DB table / endpoint. */
  layers?: LayerConfig[];
  styles?: React.CSSProperties;
}

/** A rendered layer plus everything needed to take it off the map again. */
interface LayerHandle {
  remove: () => void;
}

// ── Fetch helper (shared normaliser — matches TableBlock.tsx) ─────────────────
const BACKEND = import.meta.env.VITE_API_URL ?? "http://localhost:8000";

/** Fetches rows from a REST endpoint and normalises the response to an array. */
async function fetchRows(endpoint: string): Promise<Record<string, unknown>[]> {
  const url = endpoint.startsWith("/") ? BACKEND + endpoint : endpoint;
  const res = await axios.get<unknown>(url);
  const data = res.data;
  if (Array.isArray(data)) return data as Record<string, unknown>[];
  if (data && typeof data === "object") {
    for (const key of ["data", "results", "items", "records", "list"]) {
      const candidate = (data as Record<string, unknown>)[key];
      if (Array.isArray(candidate)) return candidate as Record<string, unknown>[];
    }
    const firstArray = Object.values(data as Record<string, unknown>).find(
      Array.isArray
    );
    if (firstArray) return firstArray as Record<string, unknown>[];
  }
  return [];
}

// ── HTML escaping ─────────────────────────────────────────────────────────────
// Leaflet's bindPopup() renders its string argument as HTML, and popup labels
// come from database rows (user-writable). Always escape them.
function escapeHtml(value: unknown): string {
  return String(value).replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ] as string
  );
}

// ── Default marker icon ───────────────────────────────────────────────────────
// Inline SVG pin — self-contained (no CDN, no bundler asset config needed).
// To use an image icon instead, see the CUSTOM ICONS extension at the bottom.
const DEFAULT_PIN_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="25" height="41" viewBox="0 0 25 41">' +
  '<path d="M12.5 0C5.6 0 0 5.6 0 12.5c0 9.4 12.5 28.5 12.5 28.5S25 21.9 25 12.5C25 5.6 19.4 0 12.5 0z" fill="#2A81CB" stroke="#1a5a94" stroke-width="1"/>' +
  '<circle cx="12.5" cy="12.5" r="5" fill="white"/></svg>';

const defaultIcon = L.divIcon({
  className: "",
  html: DEFAULT_PIN_SVG,
  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [0, -34],
});

// ── Choropleth colour scale (sequential: white → dark-red) ───────────────────
function choroplethColor(value: number, min: number, max: number): string {
  const t = max === min ? 0 : (value - min) / (max - min);
  // 5-step sequential scale (white → red)
  const stops = ["#FFEDA0", "#FED976", "#FEB24C", "#FC4E2A", "#800026"];
  const idx = Math.min(Math.floor(t * stops.length), stops.length - 1);
  return stops[idx];
}

// ────────────────────────────────────────────────────────────────────────────
//  Per-layer renderers — each returns a LayerHandle (or null when skipped)
// ────────────────────────────────────────────────────────────────────────────

// ===== POINTS LAYER ==========================================================
// Renders each DB row as a Leaflet marker.  Required columns: latitude, longitude.
// Optional: any column for the popup label (labelField).
//
// To customise markers:
//   - Custom icon:   pass `{ icon: myIcon }` to L.marker — see the
//                    "CUSTOM ICONS" extension block at the bottom of this file.
//   - Rich popups:   build an HTML string — escape every dynamic value with
//                    escapeHtml() before concatenating.
// =============================================================================
async function renderPointsLayer(
  map: L.Map,
  layer: LayerConfig
): Promise<LayerHandle | null> {
  const latF = layer.latitudeField;
  const lngF = layer.longitudeField;
  const lblF = layer.labelField;
  const endpoint = layer.dataBinding?.endpoint;
  if (!endpoint || !latF || !lngF) return null;

  const rows = await fetchRows(endpoint);
  const group = L.layerGroup();
  for (const row of rows) {
    const lat = parseFloat(String(row[latF]));
    const lng = parseFloat(String(row[lngF]));
    if (isNaN(lat) || isNaN(lng)) continue;
    const marker = L.marker([lat, lng], { icon: defaultIcon });
    const label = lblF ? row[lblF] : undefined;
    if (label !== undefined) marker.bindPopup(escapeHtml(label));
    marker.addTo(group);
  }
  group.addTo(map);
  return { remove: () => map.removeLayer(group) };
}

// ===== GEOJSON LAYER =========================================================
// Renders a GeoJSON column (geometry) as polygons / lines / points on the map.
// Required columns: geometry (string — a valid GeoJSON FeatureCollection or Feature).
// Optional: labelField for click popups.
//
// To customise polygon style:
//   Pass a `style` option to L.geoJSON below.
//   See: https://leafletjs.com/reference.html#geojson-style
// =============================================================================
async function renderGeoJsonLayer(
  map: L.Map,
  layer: LayerConfig
): Promise<LayerHandle | null> {
  const geojsonF = layer.geojsonField;
  const lblF = layer.labelField;
  const endpoint = layer.dataBinding?.endpoint;
  if (!endpoint || !geojsonF) return null;

  const rows = await fetchRows(endpoint);
  const group = L.layerGroup();
  for (const row of rows) {
    try {
      const raw = row[geojsonF];
      const feature = typeof raw === "string" ? JSON.parse(raw) : raw;
      L.geoJSON(feature as GeoJSON.GeoJsonObject, {
        onEachFeature: lblF
          ? (feat, leafletLayer) => {
              const label = feat?.properties?.[lblF];
              if (label != null) leafletLayer.bindPopup(escapeHtml(label));
            }
          : undefined,
      }).addTo(group);
    } catch {
      console.warn(`[MapBlock] ${layer.name}: could not parse geometry row`);
    }
  }
  group.addTo(map);
  return { remove: () => map.removeLayer(group) };
}

// ===== CHOROPLETH LAYER ======================================================
// Colours GeoJSON polygons by a numeric `value` column using a sequential scale.
// Required columns: geometry (GeoJSON string), value (float).
// Optional: labelField for click popups.
//
// Graceful degradation: if no valueField is set, falls back to a plain GeoJSON
// render with a console warning (never crashes).
//
// To customise the colour scale:
//   Modify `choroplethColor()` above or replace it with a d3-scale call.
// =============================================================================
async function renderChoroplethLayer(
  map: L.Map,
  layer: LayerConfig
): Promise<LayerHandle | null> {
  const geojsonF = layer.geojsonField;
  const valueF = layer.valueField;
  const lblF = layer.labelField;
  const endpoint = layer.dataBinding?.endpoint;
  if (!endpoint || !geojsonF) return null;

  if (!valueF) {
    console.warn(
      `[MapBlock] ${layer.name}: choropleth layer has no valueField — falling back to plain GeoJSON`
    );
  }

  const rawRows = await fetchRows(endpoint);
  const parsed: { feature: unknown; value: number }[] = [];
  let mn = Infinity;
  let mx = -Infinity;
  for (const row of rawRows) {
    try {
      const raw = row[geojsonF];
      const feature = typeof raw === "string" ? JSON.parse(raw) : raw;
      const val = valueF ? parseFloat(String(row[valueF])) : 0;
      if (!isNaN(val)) {
        mn = Math.min(mn, val);
        mx = Math.max(mx, val);
      }
      parsed.push({ feature, value: isNaN(val) ? 0 : val });
    } catch {
      console.warn(`[MapBlock] ${layer.name}: could not parse geometry row`);
    }
  }
  const minVal = mn === Infinity ? 0 : mn;
  const maxVal = mx === -Infinity ? 1 : mx;

  const group = L.layerGroup();
  for (const { feature, value } of parsed) {
    L.geoJSON(feature as GeoJSON.GeoJsonObject, {
      style: () => ({
        fillColor: valueF ? choroplethColor(value, minVal, maxVal) : "#3388ff",
        weight: 1,
        opacity: 1,
        color: "#666",
        fillOpacity: 0.7,
      }),
      onEachFeature: (feat, leafletLayer) => {
        const parts: string[] = [];
        if (lblF && feat?.properties?.[lblF] != null)
          parts.push(escapeHtml(feat.properties[lblF]));
        if (valueF) parts.push(`Value: ${escapeHtml(value)}`);
        if (parts.length) leafletLayer.bindPopup(parts.join("<br/>"));
      },
    }).addTo(group);
  }
  group.addTo(map);

  // ── Simple choropleth legend (bottom-right Leaflet control) ────────────────
  let legend: L.Control | null = null;
  if (valueF && parsed.length > 0) {
    legend = new L.Control({ position: "bottomright" });
    legend.onAdd = () => {
      const div = L.DomUtil.create("div", "leaflet-control-choropleth-legend");
      div.style.cssText =
        "background:white;padding:8px 12px;border-radius:4px;" +
        "box-shadow:0 1px 4px rgba(0,0,0,.3);font-size:12px;line-height:1.6;";
      const stops = ["#FFEDA0", "#FED976", "#FEB24C", "#FC4E2A", "#800026"];
      const step = (maxVal - minVal) / (stops.length - 1);
      div.innerHTML =
        `<strong style="display:block;margin-bottom:4px">${escapeHtml(layer.name ?? "")}</strong>` +
        stops
          .map((c, i) => {
            const v = (minVal + step * i).toFixed(1);
            return (
              `<span style="display:inline-block;width:14px;height:14px;` +
              `background:${c};margin-right:4px;vertical-align:middle;` +
              `border:1px solid #999"></span>${v}`
            );
          })
          .join("&nbsp;&nbsp;");
      return div;
    };
    legend.addTo(map);
  }

  return {
    remove: () => {
      map.removeLayer(group);
      legend?.remove();
    },
  };
}

// ===== HEATMAP LAYER =========================================================
// Renders intensity data as a smooth heatmap using leaflet.heat.
// Required columns: latitude (float), longitude (float).
// Optional: weight (0-1 float, defaults to 0.5 if absent).
//
// To adjust heatmap appearance:
//   Modify the options passed to L.heatLayer() below:
//   radius, blur, maxZoom, max, gradient.
//   See: https://github.com/Leaflet/Leaflet.heat#reference
// =============================================================================
async function renderHeatLayer(
  map: L.Map,
  layer: LayerConfig
): Promise<LayerHandle | null> {
  const latF = layer.latitudeField;
  const lngF = layer.longitudeField;
  const wgtF = layer.weightField;
  const endpoint = layer.dataBinding?.endpoint;
  if (!endpoint || !latF || !lngF) return null;

  try {
    // leaflet.heat registers itself on the global L
    await import("leaflet.heat");
  } catch {
    console.warn(
      "[MapBlock] leaflet.heat not installed — run: npm install leaflet.heat"
    );
    return null;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const L_ = L as any;
  if (typeof L_.heatLayer !== "function") {
    console.warn("[MapBlock] L.heatLayer not available — is leaflet.heat installed?");
    return null;
  }

  const rows = await fetchRows(endpoint);
  const points: [number, number, number][] = [];
  for (const row of rows) {
    const lat = parseFloat(String(row[latF]));
    const lng = parseFloat(String(row[lngF]));
    if (isNaN(lat) || isNaN(lng)) continue;
    const weight = wgtF ? parseFloat(String(row[wgtF])) || 0.5 : 0.5;
    points.push([lat, lng, weight]);
  }
  const heat = L_.heatLayer(points, {
    radius: 25,
    blur: 15,
    maxZoom: 17,
  }).addTo(map);
  return { remove: () => map.removeLayer(heat) };
}

// ────────────────────────────────────────────────────────────────────────────
//  Layer dispatcher — picks the right renderer for each layer
// ────────────────────────────────────────────────────────────────────────────
async function renderLayer(
  map: L.Map,
  layer: LayerConfig
): Promise<LayerHandle | null> {
  switch (layer.type) {
    case "points":
      return renderPointsLayer(map, layer);
    case "geojson":
      return renderGeoJsonLayer(map, layer);
    case "choropleth":
      return renderChoroplethLayer(map, layer);
    case "heatmap":
      return renderHeatLayer(map, layer);
    default:
      // Unknown / unset type: fall back to points
      console.warn(
        `[MapBlock] Unknown layer type "${layer.type}" for layer "${layer.name}" — falling back to points`
      );
      return renderPointsLayer(map, layer);
  }
}

// ────────────────────────────────────────────────────────────────────────────
//  MapBlock — public component exported and consumed by generated pages
// ────────────────────────────────────────────────────────────────────────────
export function MapBlock({ id, title, mapConfig, layers = [], styles }: MapBlockProps) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const mapRef = useRef<L.Map | null>(null);

  const lat = mapConfig?.centerLatitude ?? 0;
  const lng = mapConfig?.centerLongitude ?? 0;
  const zoom = mapConfig?.zoom ?? 10;

  const containerStyle: React.CSSProperties = {
    height: "450px",
    width: "100%",
    ...styles,
  };

  // Create the Leaflet map once, destroy it on unmount.
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return;
    const map = L.map(containerRef.current, { scrollWheelZoom: true }).setView(
      [lat, lng],
      zoom
    );
    // OpenStreetMap tile layer — no API key required. Attribution is mandatory
    // under the OSM tile usage policy; keep it if you swap the tile server.
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);
    mapRef.current = map;
    return () => {
      map.remove();
      mapRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Keep centre / zoom in sync with props after mount.
  useEffect(() => {
    mapRef.current?.setView([lat, lng], zoom);
  }, [lat, lng, zoom]);

  // (Re)build the data layers whenever the layer config changes.
  const layersKey = JSON.stringify(layers);
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    let cancelled = false;
    const handles: LayerHandle[] = [];

    // Static fallback marker when no layers are defined
    if (layers.length === 0) {
      const marker = L.marker([lat, lng], { icon: defaultIcon })
        .bindPopup("Map centre")
        .addTo(map);
      handles.push({ remove: () => map.removeLayer(marker) });
    }

    (async () => {
      // Render in order (bottom → top)
      for (const layer of layers) {
        try {
          const handle = await renderLayer(map, layer);
          if (!handle) continue;
          if (cancelled) handle.remove();
          else handles.push(handle);
        } catch (err) {
          console.warn(`[MapBlock] ${layer.name} fetch error:`, err);
        }
      }
    })();

    return () => {
      cancelled = true;
      handles.forEach((h) => h.remove());
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [layersKey]);

  return (
    <div id={id}>
      {title && (
        <h3 style={{ marginBottom: "8px", fontWeight: 600 }}>{title}</h3>
      )}
      <div ref={containerRef} style={containerStyle} />
    </div>
  );
}

// ============================================================
//  ===== EXTENSION: CUSTOM MARKER ICONS / IMAGE POPUPS =====
//
//  Uncomment and adapt the blocks below to use custom icons or
//  embed images / HTML in popups.  No metamodel changes required.
//
//  ── Custom Leaflet icon ──────────────────────────────────────
//
//  import customIconPng from "../assets/pin.png";   // add your image
//
//  const myIcon = L.icon({
//    iconUrl: customIconPng,
//    iconSize: [32, 32],      // [width, height] in pixels
//    iconAnchor: [16, 32],    // point on the icon that corresponds to the marker position
//    popupAnchor: [0, -32],   // where the popup opens relative to the icon
//  });
//
//  Then inside renderPointsLayer, replace:
//    L.marker([lat, lng], { icon: defaultIcon })
//  with:
//    L.marker([lat, lng], { icon: myIcon })
//
//  ── Image popup ──────────────────────────────────────────────
//
//  // Assuming your DB table has an "image_url" column:
//  // (escape every dynamic value — popups render HTML)
//  const imgUrl = escapeHtml(row["image_url"] ?? "");
//  marker.bindPopup(
//    (imgUrl ? `<img src="${imgUrl}" alt="marker" style="max-width:180px"/>` : "") +
//    `<p>${escapeHtml(label)}</p>`
//  );
//
//  ── Per-layer colour override (points layer) ─────────────────
//
//  const coloredIcon = (color: string) =>
//    L.divIcon({
//      className: "",
//      html: DEFAULT_PIN_SVG.replace("#2A81CB", color),
//      iconSize: [25, 41],
//      iconAnchor: [12, 41],
//    });
//
//  L.marker([lat, lng], { icon: coloredIcon("#e74c3c") })
// ============================================================
