"""
Provenance of generated output: which BESSER version produced it.

The version is the package version from ``setup.cfg``, and the build commit is
``BESSER_BUILD_SHA`` when the Docker build set it. The provenance
file carries no timestamp, so regenerating the same model yields the same bytes.
"""
import configparser
import io
import os
import zipfile
from functools import lru_cache
from importlib import metadata
from pathlib import Path
from typing import Mapping, Optional

PROVENANCE_FILENAME = "BESSER_GENERATION.md"
BESSER_URL = "https://github.com/BESSER-PEARL/BESSER"


@lru_cache(maxsize=1)
def get_besser_version() -> str:
    """The version of the BESSER code that is running, or ``"unknown"``.

    A source checkout (editable install, Docker image) reads the ``setup.cfg``
    beside the package: package metadata found on ``sys.path`` can belong to
    another install. A wheel install has no ``setup.cfg`` and uses its metadata.
    """
    setup_cfg = Path(__file__).resolve().parents[2] / "setup.cfg"
    if setup_cfg.is_file():
        parser = configparser.ConfigParser()
        parser.read(setup_cfg, encoding="utf-8")
        version = parser.get("metadata", "version", fallback="").strip()
        if version and parser.get("metadata", "name", fallback="") == "besser":
            return version
    try:
        return metadata.version("besser")
    except metadata.PackageNotFoundError:
        return "unknown"


def get_build_sha() -> Optional[str]:
    """The commit the Docker image was built from, or None when not stamped."""
    sha = os.environ.get("BESSER_BUILD_SHA", "").strip()
    return sha if sha and sha != "unknown" else None


def _inline(value) -> str:
    """Keep a value on one line and inside its backticks."""
    return " ".join(str(value).split()).replace("`", "'")


def generation_provenance_markdown(
    generator: str,
    options: Optional[Mapping[str, object]] = None,
) -> str:
    """The ``BESSER_GENERATION.md`` text for one generation.

    ``options`` must hold only user-facing settings that shape the output
    (dbms, project name, ...), never credentials.
    """
    lines = [
        "# Generated by BESSER",
        "",
        f"This code was generated by [BESSER]({BESSER_URL}), a low-code, model-driven platform.",
        "",
        f"- BESSER version: `{_inline(get_besser_version())}`",
    ]
    build_sha = get_build_sha()
    if build_sha:
        lines.append(f"- BESSER build: `{_inline(build_sha)}`")
    lines.append(f"- Generator: `{_inline(generator)}`")
    shown = {k: v for k, v in (options or {}).items() if v is not None and v != ""}
    if shown:
        lines.append("- Options:")
        lines.extend(f"  - {_inline(k)}: `{_inline(v)}`" for k, v in shown.items())
    lines += [
        "",
        "Regenerating from the model overwrites these files; re-apply any manual changes afterwards.",
        "",
    ]
    return "\n".join(lines)


def write_generation_provenance(
    directory: str,
    generator: str,
    options: Optional[Mapping[str, object]] = None,
) -> str:
    """Write ``BESSER_GENERATION.md`` at the root of ``directory``; returns its path."""
    path = os.path.join(directory, PROVENANCE_FILENAME)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(generation_provenance_markdown(generator, options))
    return path


def add_generation_provenance_to_zip(
    zip_buffer: io.BytesIO,
    generator: str,
    options: Optional[Mapping[str, object]] = None,
) -> io.BytesIO:
    """Append ``BESSER_GENERATION.md`` to the root of an in-memory zip, unless present."""
    zip_buffer.seek(0)
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED) as archive:
        if PROVENANCE_FILENAME not in archive.namelist():
            # A fixed date keeps the entry itself byte-identical across runs.
            info = zipfile.ZipInfo(PROVENANCE_FILENAME, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, generation_provenance_markdown(generator, options))
    zip_buffer.seek(0)
    return zip_buffer
