"""Phase 3 must block an aggregate that no request can create.

Run 9a6063ed (2026-09-18) delivered a hotel app that passed every static
gate - imports, mappers, star-import names, 61 routes, Person/Employee/
Guest/Room all creating fine - and could not create a Booking by ANY
sequence of requests. Phase 2 had implemented the gap analyser's task
("validation in create_booking that the guests do not exceed the room
capacities across all BookedRooms") at insert time, when a Booking has no
BookedRooms yet because a BookedRoom needs a Booking id::

    with a guest    -> 400 "Total number of guests (1) exceeds room capacity (0)"
    without a guest -> 400 "At least 1 Guest(s) required"

Bill and BookedRoom, which require a Booking, were dead with it. Nothing
static sees this: the code is ordinary, the schema valid, and whether the
``raise`` is reachable is a data-flow question. The probe reports its observed
failures and unresolved dependencies, not a universal claim from guessed
inputs. A valid API workflow can resolve an unverified create route without
weakening business validation. The fixture is run 9a6063ed's backend, verbatim.
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path

import pytest

from besser.spec_driven_agent.validation.constructibility import (
    PREFIX,
    UNVERIFIED_PREFIX,
    _NetworkBlocked,
    _build_payload,
    _install_network_guard,
    _is_local_host,
    _issues_from_report,
    _run_probe,
    _sample,
    collect_constructibility_issues,
    collect_constructibility_report,
)
from besser.spec_driven_agent.execution.process import _safe_subprocess_env
from besser.spec_driven_agent.pipeline.orchestrator import LLMOrchestrator, ValidationIssue, _classify_issue

pytest.importorskip("fastapi")
pytest.importorskip("httpx")

FIXTURE = Path(__file__).parent / "fixtures" / "run_9a6063ed"


@pytest.fixture
def workspace(tmp_path):
    shutil.copytree(FIXTURE, tmp_path, dirs_exist_ok=True)
    return str(tmp_path)


# --------------------------------------------------------------- the live run


def test_the_live_run_cannot_create_a_booking(workspace):
    issues = collect_constructibility_issues(workspace)
    assert len(issues) == 3, issues
    [issue] = [i for i in issues if "POST /booking/" in i]
    assert issue.startswith(f"{UNVERIFIED_PREFIX} web_app/backend: POST /booking/ -")
    assert "autogenerated input was refused (400:" in issue
    # The refused payload carried a guest, so it is the guard, not the
    # multiplicity, that refused it - and the guard is what has to move.
    assert '"guest": [' in issue
    assert "Dependent create probes for Bill, BookedRoom" in issue
    assert "those children require a Booking first" in issue
    assert "atomic valid aggregate-creation workflow" in issue
    assert "retaining the rule" in issue
    assert "every schema-valid" not in issue


def test_a_recollection_reports_the_same_thing(workspace):
    """The fix loop compares blocker counts across rounds."""
    assert collect_constructibility_issues(workspace) == collect_constructibility_issues(workspace)


class _Usage:
    estimated_cost = 0.0

    def summary(self) -> dict:
        return {"api_calls": 0, "cost_usd": 0.0}


class _ScriptedClient:
    model = "test-model"
    usage = _Usage()
    max_tokens = 4096

    def chat(self, system=None, messages=None, tools=None, **kwargs):
        return {"stop_reason": "end_turn", "content": []}


def test_the_phase3_sweep_carries_the_blocker(workspace):
    """What shipped as "0 blockers" must come out of the sweep as one."""
    from besser.BUML.metamodel.structural import Class, DomainModel

    orch = LLMOrchestrator(
        llm_client=_ScriptedClient(),
        domain_model=DomainModel(name="Hotel", types={Class(name="Booking")}),
        output_dir=workspace,
        enable_tracing=False, enable_checkpointing=False,
        enable_toolchain_validation=False,
    )
    issues = orch._collect_validation_issues()
    blockers = [i.message for i in issues if i.severity == "blocker"]
    assert [b for b in blockers if UNVERIFIED_PREFIX in b], blockers


# ----------------------------------------------------- a fresh generated app


def _scaffold(tmp_path) -> str:
    """A generator-fresh backend: Room (with an enum) and Booking, which
    needs a Room. Returns the workspace root."""
    from besser.BUML.metamodel.structural import (
        BinaryAssociation, Class, DateType, DomainModel, Enumeration,
        EnumerationLiteral, IntegerType, Multiplicity, Property,
    )
    from besser.generators.backend import BackendGenerator

    status = Enumeration(name="RoomStatus", literals={
        EnumerationLiteral(name="AVAILABLE"), EnumerationLiteral(name="MAINTENANCE"),
    })
    room = Class(name="Room", attributes={
        Property(name="roomNumber", type=IntegerType),
        Property(name="status", type=status),
    })
    booking = Class(name="Booking", attributes={Property(name="arrivalDate", type=DateType)})
    link = BinaryAssociation(name="room_booking", ends={
        Property(name="room", type=room, multiplicity=Multiplicity(1, 1)),
        Property(name="bookings", type=booking, multiplicity=Multiplicity(0, "*")),
    })
    model = DomainModel(name="Hotel", types={room, booking, status}, associations={link})
    BackendGenerator(model=model, output_dir=str(tmp_path / "web_app" / "backend")).generate()
    assert (tmp_path / "web_app" / "backend" / "main_api.py").is_file()
    return str(tmp_path)


def _first_literal(tmp_path) -> str:
    """The literal the probe sends first: the first member of the generated enum."""
    text = (tmp_path / "web_app" / "backend" / "pydantic_classes.py").read_text(encoding="utf-8")
    return re.search(r"class RoomStatus\(Enum\):\s*\n\s*(\w+)\s*=", text).group(1)


def _guard_create_room(tmp_path, condition: str) -> None:
    router = tmp_path / "web_app" / "backend" / "routers" / "room.py"
    text = router.read_text(encoding="utf-8")
    head = re.search(r"async def create_room\(.*\n", text).group(0)
    guarded = head + f'    if {condition}:\n        raise HTTPException(status_code=400, detail="refused")\n'
    router.write_text(text.replace(head, guarded, 1), encoding="utf-8")


def test_a_healthy_generated_scaffold_yields_nothing(tmp_path):
    assert collect_constructibility_issues(_scaffold(tmp_path)) == []
    # Prefer native association-class attributes even when an ID-only legacy
    # alternative is advertised first. Otherwise a probe invents NOT NULL
    # failures for missing prices/quantities that the caller can supply.
    schemas = {"Link": {"allOf": [
        {"type": "object", "properties": {"target": {"type": "integer"}}, "required": ["target"]},
        {"type": "object", "properties": {"price": {"type": "number"}, "extras": {"type": "number"}},
         "required": ["price", "extras"]},
    ]}}
    schema = {"required": ["items"], "properties": {"items": {"type": "array", "items": {
        "anyOf": [{"type": "integer"}, {"$ref": "#/components/schemas/Link"}],
    }}}}
    payload, unresolved = _build_payload(schema, schemas, {"items": ("Item", True)},
                                         {"Item": 7}, {}, ("base",))
    assert not unresolved
    assert payload == {"items": [{"target": 7, "price": 1.0, "extras": 1.0}]}

    from besser.BUML.metamodel.structural import (
        AssociationClass, BinaryAssociation, Class, DomainModel, FloatType,
        Multiplicity, Property, StringType,
    )
    from besser.generators.backend import BackendGenerator

    purchase = Class(name="Purchase", attributes={Property(name="reference", type=StringType)})
    item = Class(name="Item", attributes={Property(name="label", type=StringType)})
    association = BinaryAssociation(name="PurchaseItems", ends={
        Property(name="purchases", type=purchase, multiplicity=Multiplicity(0, "*")),
        Property(name="items", type=item, multiplicity=Multiplicity(1, "*")),
    })
    line = AssociationClass(name="LineItem", attributes={Property(name="price", type=FloatType)},
                            association=association)
    native_backend = tmp_path / "native" / "backend"
    BackendGenerator(model=DomainModel(name="NativeLinks", types={purchase, item, line},
                                      associations={association}), output_dir=str(native_backend)).generate()
    report = _run_probe(str(native_backend), _safe_subprocess_env())
    assert report["boot"] == "ok", report
    assert all(e["verdict"] == "created" for e in report["entities"].values()), report
    link_attempts = report["entities"]["LineItem"]["attempts"]
    assert [a["status"] for a in link_attempts] == [409, 200], link_attempts
    assert len(report["entities"]["Item"]["attempts"]) == 2  # one bounded fresh-reference retry
    assert _issues_from_report(report, "native/backend") == []


def test_a_rule_that_another_value_satisfies_is_not_a_finding(tmp_path):
    """One 400 means "this request was wrong". The probe keeps trying."""
    workspace = _scaffold(tmp_path)
    _guard_create_room(tmp_path, f'room_data.status.value == "{_first_literal(tmp_path)}"')
    assert collect_constructibility_issues(workspace) == []


def test_a_rule_that_no_value_satisfies_is_a_finding_that_names_the_dependents(tmp_path):
    workspace = _scaffold(tmp_path)
    _guard_create_room(tmp_path, "True")
    issues = collect_constructibility_issues(workspace)
    assert len(issues) == 2, issues
    [issue] = [i for i in issues if "POST /room/" in i]
    assert issue.startswith(f"{UNVERIFIED_PREFIX} web_app/backend: POST /room/ -")
    assert "Dependent create probes for Booking could not run without a Room id" in issue
    assert "do not remove business validation" in issue


def test_a_mapper_that_fails_to_configure_is_left_to_the_smoke_check(tmp_path):
    """One defect, one blocker: ``mapper config:`` already reports it."""
    workspace = _scaffold(tmp_path)
    orm = tmp_path / "web_app" / "backend" / "sql_alchemy.py"
    orm.write_text(
        orm.read_text(encoding="utf-8") + '\nRoom.ghost = relationship("NoSuchClass")\n',
        encoding="utf-8",
    )
    assert collect_constructibility_issues(workspace) == []


def test_an_application_import_failure_is_a_located_blocker(tmp_path):
    workspace = _scaffold(tmp_path)
    orm = tmp_path / "web_app" / "backend" / "sql_alchemy.py"
    original = orm.read_text(encoding="utf-8")
    broken = original + "\nINVALID_DEFAULT = RoomStatus.awaiting_payment\n"
    orm.write_text(broken, encoding="utf-8")
    [issue] = collect_constructibility_issues(workspace)
    assert issue.startswith("application startup: web_app/backend/sql_alchemy.py line "), issue
    assert "AttributeError" in issue and "awaiting_payment" in issue
    assert _classify_issue(issue).severity == "blocker"
    assert "did not run" not in issue
    assert orm.read_text(encoding="utf-8") == broken  # probes never repair the user's source
    orm.write_text(original, encoding="utf-8")
    assert collect_constructibility_issues(workspace) == []


def test_a_workspace_without_the_fastapi_scaffold_has_nothing_to_probe(tmp_path):
    (tmp_path / "app.py").write_text("print('hi')\n", encoding="utf-8")
    assert collect_constructibility_issues(str(tmp_path)) == []


# ------------------------------------------------- report -> findings (pure)


def _report(**entities) -> dict:
    return {"boot": "ok", "entities": entities}


def _entity(verdict, status, body="", **extra) -> dict:
    return {
        "path": "/x/", "verdict": verdict,
        "attempts": [{"status": status, "outcome": verdict, "body": body, "payload": {"a": 1}}],
        **extra,
    }


def test_all_crashing_create_endpoints_are_blockers_not_a_skipped_check():
    issues = _issues_from_report(
        _report(Room=_entity("crashed", 500, "db down"), Person=_entity("crashed", 500)), "b",
    )
    assert len(issues) == 2
    assert all(issue.startswith(PREFIX) for issue in issues)
    assert all("observed a server/persistence failure" in issue for issue in issues)
    assert all("every schema-valid" not in issue for issue in issues)
    assert all(_classify_issue(issue).severity == "blocker" for issue in issues)
    assert all("did not run" not in issue for issue in issues)


def test_a_crash_beside_a_working_endpoint_is_a_finding():
    person = _entity("created", 201)
    person["attempts"].insert(0, {"status": 500, "outcome": "crashed", "body": "boom"})
    person["attempts"].insert(0, {"status": 400, "outcome": "rejected", "body": "bad guess"})
    issues = _issues_from_report(
        _report(Room=_entity("created", 200), Person=person), "b",
    )
    assert len(issues) == 1
    assert issues[0].startswith(f"{PREFIX} b: POST /x/ - observed a server/persistence failure creating Person (500: boom)")


def test_an_authentication_wall_is_not_checked():
    issues = _issues_from_report(_report(Room=_entity("unauthorized", 401)), "b")
    assert len(issues) == 1 and "requires authentication" in issues[0]
    assert issues[0].startswith(UNVERIFIED_PREFIX)


def test_a_payload_the_probe_could_not_build_is_no_verdict():
    for verdict, status, body in (("invalid", 422, "pattern mismatch"),
                                  ("rejected", 409, "identifyingNumber must be unique"),
                                  ("rejected", 400, "capacity exceeded")):
        [issue] = _issues_from_report(_report(Room=_entity(verdict, status, body)), "b")
        assert issue.startswith(UNVERIFIED_PREFIX)
        assert "guessed inputs do not prove this endpoint is broken" in issue
        assert "do not remove business validation" in issue
        assert "every schema-valid" not in issue


def test_a_missing_dependency_is_reported_as_not_checked():
    issues = _issues_from_report({"boot": "missing_dependency", "error": "No module named 'httpx'"}, "b")
    assert len(issues) == 1 and "did not run" in issues[0] and "httpx" in issues[0]
    assert _classify_issue(issues[0]).severity == "warning"


def test_a_mapper_error_is_silent():
    assert _issues_from_report({"boot": "mapper_error", "error": "x"}, "b") == []


def test_create_contract_prefix_classifies_as_blocker():
    assert _classify_issue(f"{PREFIX} b: POST /x/ cannot create an X").severity == "blocker"


# ------------------------------------------------------ run 7f918e11 (NOT NULL)

FIXTURE_7F = Path(__file__).parent / "fixtures" / "run_7f918e11"


@pytest.fixture
def workspace_7f(tmp_path):
    shutil.copytree(FIXTURE_7F, tmp_path, dirs_exist_ok=True)
    return str(tmp_path)


def test_a_not_null_insert_names_the_column_and_the_fix_site(workspace_7f):
    """Run 7f918e11: Phase 2 made BookingCreate.totalAmountDue optional and
    left the column NOT NULL and the insert without it. The finding named
    the symptom exactly and not one thing the model could edit. The fixture
    is that run's backend, verbatim."""
    issues = collect_constructibility_issues(workspace_7f)
    assert len(issues) == 3, issues
    [issue] = [i for i in issues if i.startswith(PREFIX)]
    assert issue.startswith(f"{PREFIX} web_app/backend: POST /booking/ -")
    assert "Fix site: create_booking in web_app/backend/routers/booking.py line 165" in issue
    assert "also line 220" in issue  # bulk_create_booking inserts it the same way
    assert "`totalAmountDue`" in issue and "NOT NULL" in issue
    # The dependents are still named, but the create-time-rule advice from
    # run 9a6063ed is the wrong diagnosis for a constraint failure.
    assert "Dependent create probes for Bill, ReservedRoom" in issue
    assert "create-time rule" not in issue
    assert "make the column nullable" not in issue
    assert _classify_issue(issue).severity == "blocker"


def test_the_fix_site_gives_the_fix_prompt_an_excerpt_to_quote(workspace_7f):
    """Measured on the model that failed there: with the offending lines in
    the prompt it calls modify_file on turn one (6/6); without them it reads."""
    [issue] = [i for i in collect_constructibility_issues(workspace_7f) if i.startswith(PREFIX)]
    orch = LLMOrchestrator.__new__(LLMOrchestrator)
    orch.output_dir = workspace_7f
    excerpts = orch._excerpts_for([ValidationIssue("blocker", issue)])
    assert len(excerpts) == 1, excerpts
    assert "  165|     db_booking = Booking(" in excerpts[0]


def test_a_site_and_a_missing_column_are_rendered_from_the_report():
    entity = _entity("rejected", 409, "NOT NULL constraint failed: x.total",
                     site={"file": "routers/x.py", "function": "create_x", "line": 7, "also": [30]})
    entity["attempts"][0]["missing_column"] = "total"
    [issue] = _issues_from_report(_report(X=entity), "b")
    assert "Fix site: create_x in b/routers/x.py line 7 (also line 30)" in issue
    assert "inserted without `total`" in issue


def test_a_rule_failure_does_not_invent_a_create_time_cycle():
    dependent = {"path": "/y/", "verdict": "unresolved", "unresolved": [["x", "X"]]}
    issues = _issues_from_report(_report(X=_entity("rejected", 400, "refused"), Y=dependent), "b")
    assert len(issues) == 2
    assert all(i.startswith(UNVERIFIED_PREFIX) for i in issues)
    assert "Dependent create probes for Y" in issues[0]
    assert "Creation-order check" not in issues[0]


def test_inherited_unique_identity_and_contact_fixtures_do_not_collide(workspace):
    """Luna's probe reused Person's identity for Employee and Guest, then
    instructed it to delete valid uniqueness guards. Keep the real constraints.
    """
    backend = Path(workspace) / "web_app" / "backend"
    orm = backend / "sql_alchemy.py"
    source = orm.read_text(encoding="utf-8")
    source = source.replace('class Person(Base):', 'class Person(Base):\n    identifyingNumber = mapped_column(String_(100), unique=True)')
    for field in ("email", "phone"):
        source = source.replace(f'{field}: Mapped_[str] = mapped_column(String_(100))',
                                f'{field}: Mapped_[str] = mapped_column(String_(100), unique=True)')
    orm.write_text(source, encoding="utf-8")
    schemas = backend / "pydantic_classes.py"
    schemas.write_text(schemas.read_text(encoding="utf-8").replace(
        'class PersonCreate(BaseModel):', 'class PersonCreate(BaseModel):\n    identifyingNumber: str'), encoding="utf-8")
    for entity in ("Person", "Employee", "Guest"):
        router = backend / "routers" / f"{entity.lower()}.py"
        router.write_text(router.read_text(encoding="utf-8").replace(
            f"{entity}(", f"{entity}(identifyingNumber={entity.lower()}_data.identifyingNumber, ", 1), encoding="utf-8")
    report = _run_probe(str(backend), _safe_subprocess_env())
    assert report["boot"] == "ok", report
    people = [report["entities"][n] for n in ("Person", "Employee", "Guest")]
    assert all(p["verdict"] == "created" for p in people), people
    for field in ("identifyingNumber", "email", "phone"):
        assert len({p["attempts"][0]["payload"][field] for p in people}) == 3
        assert _sample(field, {"type": "string"}, 1, ordinal=1) != _sample(
            field, {"type": "string"}, 1, ordinal=2)
    assert _sample("badge", {"type": "integer"}, 1, ordinal=1, unique=True) != _sample(
        "badge", {"type": "integer"}, 1, ordinal=2, unique=True)
    assert orm.read_text(encoding="utf-8") == source


# ------------------------------------------------------------- network guard
#
# Prevention, not an incident: the probe boots LLM-authored code and nothing
# stopped it from making a real outbound call. ``_install_network_guard``
# patches ``socket.socket.connect``/``connect_ex`` for the lifetime of the
# one-shot probe subprocess. Loopback must stay allowed: on this Windows box,
# ``asyncio.run()`` itself opens a loopback socket pair for its wakeup
# self-pipe (no native ``socketpair()`` here - verified: a spy on
# ``socket.socket.connect`` records a ``('127.0.0.1', <port>)`` call during a
# bare ``asyncio.run(asyncio.sleep(0))``), so blocking loopback would break
# the probe's own event loop, not just the app under test.


def test_the_guard_allows_loopback_and_blocks_everything_else():
    import socket

    real_connect, real_connect_ex = socket.socket.connect, socket.socket.connect_ex
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    listener.bind(("127.0.0.1", 0))
    listener.listen(1)
    port = listener.getsockname()[1]
    try:
        _install_network_guard()
        # Loopback reaches the real OS connect: a live listener accepts it.
        # (One live connect only - the listener's backlog is never drained
        # with accept(), so a second real connect here would itself stall
        # for an unrelated reason. Other loopback spellings are checked
        # directly below instead of via a second live connection.)
        socket.create_connection(("127.0.0.1", port), timeout=2).close()
        assert _is_local_host("localhost")
        assert _is_local_host("::1")
        # A real outbound address never reaches the OS connect call at all.
        with pytest.raises(_NetworkBlocked):
            socket.create_connection(("93.184.216.34", 80), timeout=2)
    finally:
        socket.socket.connect, socket.socket.connect_ex = real_connect, real_connect_ex
        listener.close()


def test_the_guard_fails_open_when_it_cannot_patch(monkeypatch):
    """A probe that cannot install its guard must still run, not crash."""
    import socket

    class _Unpatchable:
        def __getattr__(self, name):
            raise RuntimeError("boom")

    monkeypatch.setattr(socket, "socket", _Unpatchable())
    _install_network_guard()  # must not raise


def _add_outbound_call_to_create_room(tmp_path) -> None:
    router = tmp_path / "web_app" / "backend" / "routers" / "room.py"
    text = router.read_text(encoding="utf-8")
    head = re.search(r"async def create_room\(.*\n", text).group(0)
    called = head + (
        "    import socket as _socket\n"
        '    _socket.create_connection(("203.0.113.1", 80), timeout=1)\n'  # RFC 5737 TEST-NET-3
    )
    router.write_text(text.replace(head, called, 1), encoding="utf-8")


def test_a_create_handler_that_dials_out_is_blocked_inside_the_probe(tmp_path):
    """End to end: a generated handler that tries a real outbound call is
    refused by the probe subprocess's own guard, not by chance network
    unreachability - the finding names the guard, not a timeout or DNS error."""
    workspace = _scaffold(tmp_path)
    _add_outbound_call_to_create_room(tmp_path)
    issues = collect_constructibility_issues(workspace)
    [issue] = [i for i in issues if "POST /room/" in i]
    assert issue.startswith(f"{PREFIX} web_app/backend: POST /room/ -")
    assert "outbound network access blocked" in issue


# --------------------------------------------------- abstract entities

def _abstract_scaffold(tmp_path):
    """A backend whose ``Person`` is ABSTRACT, with a concrete ``Patron``.

    Returns ``(workspace, model)``. The generated create route for Person is
    then guarded exactly as a real one is: it refuses, with the reason.
    """
    import re as _re

    from besser.BUML.metamodel.structural import (
        Class, DomainModel, Generalization, Property, StringType,
    )
    from besser.generators.backend import BackendGenerator

    person = Class(name="Person", attributes={Property(name="fullName", type=StringType)},
                   is_abstract=True)
    patron = Class(name="Patron", attributes={Property(name="cardNumber", type=StringType)})
    model = DomainModel(
        name="Library", types={person, patron},
        generalizations={Generalization(general=person, specific=patron)},
    )
    BackendGenerator(model=model, output_dir=str(tmp_path / "web_app" / "backend")).generate()
    router = tmp_path / "web_app" / "backend" / "routers" / "person.py"
    text = router.read_text(encoding="utf-8")
    head = _re.search(r"async def create_person\(.*\n", text).group(0)
    guarded = head + (
        '    raise HTTPException(status_code=422, '
        'detail="Person is abstract; create a Patron instead")\n'
    )
    router.write_text(text.replace(head, guarded, 1), encoding="utf-8")
    return str(tmp_path), model


def test_an_abstract_entity_is_not_probed_for_construction(tmp_path):
    """A router that refuses to instantiate an abstract class is CORRECT, and
    POSTing to it manufactures a blocker no repair can clear.

    Walked end to end on run gpt-5.6-terra-hzllh0l6: the project marks
    ``Person`` abstract, the generated router answers
    ``422 Person is abstract; create a Patron or Librarian instead``, and the
    recipe's sole remaining blocker was the probe's own guessed POST being
    refused. 17 Phase 3 rounds, every one zero writes, 108 turns, $0.96,
    blockers pinned at 1 throughout. Without the model the probe cannot know,
    so the finding still appears - that is the control below.
    """
    workspace, model = _abstract_scaffold(tmp_path)

    blind = collect_constructibility_issues(workspace)
    assert any("/person" in issue.lower() for issue in blind), (
        "control: with no model to read, the refusal is still reported"
    )

    informed = collect_constructibility_report(workspace, model)
    assert not [i for i in informed["issues"] if "/person" in i.lower()], informed["issues"]
    assert informed["backends"][0].get("skipped_abstract") == ["Person"]
    # The concrete subclass is still probed.
    assert "Patron" in (informed["backends"][0].get("entities") or {})
