@startuml
skinparam groupInheritance 2

class Library {
+ name: str
+ address: str
}

class Book{
+ tittle: str
+ pages: int
+ edition: date
}

class Literature extends Book{
}

class Science extends Book{
}

class Fantasy {
}

class Author {
+ name: str
+ email: str
+ notify(sms: str = "message", contact_method: ContactM)
+ {abstract} func(): str
}

enum ContactM {
    EMAIL
    TELEPHONE
    LETTER
}

abstract class Platform{}

Book "*" -- "1..*" Author: writtenBy
Library "1" -- Book: has
Book <|-- Fantasy
@enduml