import keyword
import logging
import re
from typing import Any
import xml.etree.ElementTree as ET

from besser.generators.alloy.translate_ocl_alloy import DATES_DICT
logger = logging.getLogger(__name__)

class AlloyToBUML:
    """Converts Alloy XML instances to BUML object diagrams."""

    def __init__(self, xml_file: str):
        """
        Initializes the converter with the given Alloy XML file.

        Args:
            xml_file: Path to Alloy XML file
        """
        self.xml_file = xml_file
        self.tree = ET.parse(xml_file)
        self.root = self.tree.getroot()

        self.builtin_sigs = {'seq/Int', 'Int', 'String', 'univ', 'boolean/Bool',
                            'boolean/True', 'boolean/False'}

        # Parse signatures and fields from the XML
        self.signatures = {}  # sig_id -> {label, atoms}
        self.fields = {}  # field_id -> {label, parent_id, tuples}
        self.atoms_by_sig = {}  # sig_label -> [atoms]

        for sig in self.root.findall('.//sig'):
            sig_id = sig.get('ID')
            sig_label = sig.get('label')
            parent_id = sig.get('parentID')

            # Ignore built-in signatures
            if sig_label in self.builtin_sigs:
                continue

            atoms = [atom.get('label') for atom in sig.findall('atom')]

            self.signatures[sig_id] = {
                'label': sig_label,
                'atoms': atoms,
                'builtin': sig.get('builtin') == 'yes',
                'parent_id': parent_id,
            }

            # Organize atoms by signature label
            if not self.signatures[sig_id]['builtin']:
                self.atoms_by_sig[sig_label] = atoms

        for field in self.root.findall('.//field'):
            field_id = field.get('ID')
            field_label = field.get('label')
            parent_id = field.get('parentID')

            raw_tuples = [
                [atom.get('label') for atom in tuple_elem.findall('atom')]
                for tuple_elem in field.findall('tuple')
            ]
            tuples = [(atoms[0], atoms[1]) for atoms in raw_tuples if len(atoms) >= 2]

            self.fields[field_id] = {
                'label': field_label,
                'parent_id': parent_id,
                'tuples': tuples,
                'raw_tuples': raw_tuples,
            }

    def _date_sig_label(self) -> str | None:
        """Returns the label of the 'Date' signature (e.g., 'this/Date') if it exists."""
        for sig_label in self.atoms_by_sig:
            if get_class_name(sig_label) == "Date":
                return sig_label
        return None

    def _date_signature_class_names(self) -> set[str]:
        """Returns the class names of the Alloy date signatures.

        These are ``Date`` and its concrete ``DateN`` children (the per-date
        ``one sig`` generated by :func:`generate_dates_and_order`). They are
        detected by walking the ``parent_id`` chain up to the ``Date``
        signature, so they are excluded even when :data:`DATES_DICT` is empty.
        """
        date_parent_ids = {
            sig_id
            for sig_id, sig_data in self.signatures.items()
            if get_class_name(sig_data["label"]) == "Date"
        }
        date_ids = set(date_parent_ids)
        changed = True
        while changed:
            changed = False
            for sig_id, sig_data in self.signatures.items():
                if sig_id in date_ids:
                    continue
                if sig_data.get("parent_id") in date_ids:
                    date_ids.add(sig_id)
                    changed = True
        return {
            get_class_name(self.signatures[sig_id]["label"])
            for sig_id in date_ids
            if sig_id in self.signatures
        }

    def _date_value_expression(self, atom_label: str, as_datetime: bool) -> str:
        """Returns the BUML code expression for a date-typed attribute value.

        When *as_datetime* is ``True`` it emits a real ``datetime.date(...)``
        constant, so the generated code executes against DateType attributes.
        Otherwise it delegates to :func:`get_date_value`, which returns an
        ISO-8601 string literal that the frontend converter can consume.
        """
        if not as_datetime:
            return get_date_value(atom_label)
        iso = get_date_value(atom_label).strip('"')
        year, month, day = iso.split("-")
        return f"datetime.date({int(year)}, {int(month)}, {int(day)})"

    def is_date_value(self, atom_label: str) -> bool:
        """
        Determines if an atom represents a date value.
        """
        base = get_class_name(atom_label.split("$")[0])
        if base in DATES_DICT or DATE_SIG_PATTERN.match(base):
            return True
        date_sig_label = self._date_sig_label()
        return bool(date_sig_label and atom_label in self.atoms_by_sig[date_sig_label])

    def is_object_reference(self, atom_label: str) -> bool:
        """
        Determines if an atom is a reference to another domain object.
        Args:
            atom_label: atom label to check

        Returns:
            True if it is a reference to an object, False if it is primitive
        """
        # Domain objects are represented with format ClassName$N
        if '$' in atom_label:
            base = atom_label.split('$')[0]

            # Exclude special types and types that are not domain objects
            if  base.startswith('ENUM_'): 
                return False  

            # Check if it exists in atoms_by_sig with the prefix this/
            for sig_label in self.atoms_by_sig:
                class_name = get_class_name(sig_label)
                if (class_name == base
                        and atom_label in self.atoms_by_sig[sig_label]
                        and class_name not in ['Str', 'Bool', 'True', 'False']):
                    return True
        return False

    def _str_signature(self) -> tuple[str, str] | None:
        """Returns the ``(label, sig_id)`` of the 'Str' signature (e.g., ``('strings/Str', '24')``)."""
        for sig_id, sig_data in self.signatures.items():
            if get_class_name(sig_data['label']) == "Str" and not sig_data.get('builtin'):
                return sig_data['label'], sig_id
        return None

    def is_str_value(self, atom_label: str) -> bool:
        """
        Determines if an atom is a value of the Alloy 'Str' signature.

        String atoms are represented with format ``<str_sig_label>$N``
        (e.g., ``'strings/Str$0'``).
        """
        str_signature = self._str_signature()
        if str_signature is None:
            return False
        str_sig_label = str_signature[0]
        return atom_label in self.atoms_by_sig.get(str_sig_label, [])

    def _str_data_tuples(self, atom_label: str) -> list[tuple[str, str]]:
        """Returns the ``(index, Char atom)`` pairs composing *atom_label*'s string.

        The ``data`` field of the ``Str`` signature stores one ``(Str, index, Char)``
        tuple per character (e.g., ``('strings/Str$0', '0', 'strings/z$0')``).
        """
        str_signature = self._str_signature()
        if str_signature is None:
            return []
        _, str_sig_id = str_signature
        for field_data in self.fields.values():
            if field_data['parent_id'] != str_sig_id:
                continue
            pairs = []
            for atoms in field_data['raw_tuples']:
                if len(atoms) >= 3 and atoms[0] == atom_label:
                    pairs.append((atoms[1], atoms[2]))
            return pairs
        return []

    def _str_value_expression(self, atom_label: str) -> str:
        """Returns the BUML code expression for a string-typed attribute value."""
        return f'"{get_str_value(self._str_data_tuples(atom_label))}"'

    def _pair_association_fields(self) -> dict[str, frozenset]:
        """
        Pairs the two ends of the same bidirectional association.

        The Alloy encoding represents a bidirectional association as two fields with exactly transposed
        sets of tuples. This mapping allows one to deduplicate only those two halves without collapsing
        distinct associations between the same pair of objects.
        """
        field_tuples: dict[str, set[tuple]] = {}
        for field_data in self.fields.values():
            label = field_data['label']
            field_tuples[label] = set(field_data['tuples'])

        used: set[str] = set()
        paired: dict[str, frozenset] = {}
        for field_label, tuples in field_tuples.items():
            if field_label in used or not tuples:
                continue

            transposed = {(to_atom, from_atom) for from_atom, to_atom in tuples}
            partner = None
            for other_label, other_tuples in field_tuples.items():
                if other_label in used or other_label == field_label or not other_tuples:
                    continue
                if other_tuples == transposed:
                    partner = other_label
                    break

            if partner:
                assoc = frozenset([field_label, partner])
                paired[field_label] = assoc
                paired[partner] = assoc
                used.update([field_label, partner])
            else:
                paired[field_label] = frozenset([field_label])

        return paired

    def _signature_depth(self, sig_id: str | None) -> int:
        """Returns the depth of *sig_id* in the inheritance tree."""
        depth = 0
        current_id = sig_id
        while current_id and current_id in self.signatures:
            parent_id = self.signatures[current_id].get('parent_id')
            if not parent_id or parent_id not in self.signatures:
                break
            depth += 1
            current_id = parent_id
        return depth

    def _leaf_class_for(self, atom_label: str) -> str | None:
        """Returns the most specific concrete class that contains *atom_label*."""
        containing = [sig for sig in self._domain_signatures if atom_label in sig['atoms']]
        if not containing:
            return None
        leaf_sig = max(
            containing,
            key=lambda sig: (sig['depth'], -len(sig['atoms']), sig['class_name'])
        )
        return leaf_sig['class_name']

    def generate_object_diagram(
        self, date_as_datetime: bool = True, for_editor: bool = True
    ) -> str:
        """
        Generates BUML code for the object diagram derived from the XML.

        Only the most specific concrete class of each atom is instantiated,
        inherited attributes are incorporated, and multiple associations
        between the same classes or objects are preserved.

        Args:
            date_as_datetime: Only used when *for_editor* is ``False``. When
                ``True`` (default), date-typed attribute values are emitted as
                real ``datetime.date(...)`` constants, matching the convention
                used by ``BUMLModelIntegrator.generate_integrated_model`` so
                the generated code is directly executable/importable on its
                own. When ``False``, they are emitted as ISO-8601 strings
                instead; ``object_buml_to_json`` accepts both forms.
            for_editor: When ``True`` (default), emit the code in the "editor"
                dialect consumed by the web editor's ``object_buml_to_json``
                converter (development version). Objects are always built
                through ``Class("name").attributes(...).build()``, attribute
                values are emitted as literal constants (dates as ISO-8601
                strings), and links are emitted as one ``obj.role = target``
                assignment per target. This dialect is NOT meant to be executed
                (repeated assignments for many-valued ends collapse at
                runtime); it is only used to feed ``object_buml_to_json``. When
                ``False``, the executable dialect is emitted instead.
        """
        code_lines = [
            "from besser.BUML.metamodel.object import ObjectModel",
            "import datetime",
            "",
        ]

        # Identify the domain classes. The enumeration signatures and the
        # Alloy date signatures (this/Date and its concrete this/DateN siblings)
        # should not be materialized as objects.
        date_class_names = self._date_signature_class_names()
        domain_classes = set()
        for sig_label, atoms in self.atoms_by_sig.items():
            if not sig_label.startswith("this/"):
                continue
            class_name = get_class_name(sig_label)
            if not is_domain_class_name(class_name):
                continue
            if class_name in date_class_names:
                continue
            if atoms and all(is_enum_value(atom) for atom in atoms):
                continue
            domain_classes.add(class_name)

        self._domain_signatures = []
        for sig_id, sig_data in self.signatures.items():
            class_name = get_class_name(sig_data['label'])
            if class_name not in domain_classes:
                continue
            self._domain_signatures.append({
                'class_name': class_name,
                'atoms': set(sig_data['atoms']),
                'depth': self._signature_depth(sig_id),
            })

        created_objects = {}  # atom_label -> variable_name
        relations = []  # [(from_var, relation_name, to_atom, field_name), ...]

        for sig_label, atoms in self.atoms_by_sig.items():
            class_name = get_class_name(sig_label)

            if class_name not in domain_classes:
                continue

            for i, atom_label in enumerate(atoms):
                if self._leaf_class_for(atom_label) != class_name:
                    continue

                obj_var = f"{class_name.lower()}_{i}_obj"
                obj_name = atom_label.replace('$', '_')

                created_objects[atom_label] = obj_var
                attributes = {}

                # Traverse all fields to also include attributes and associations
                # inherited from ancestor classes.
                for field_data in self.fields.values():
                    field_name = field_data['label']
                    tuples = field_data['tuples']
                    attr_name = remove_class_prefix(field_name, class_name)

                    for tuple_from, tuple_to in tuples:
                        if tuple_from != atom_label:
                            continue

                        if self.is_date_value(tuple_to):
                            if for_editor:
                                attributes[attr_name] = self._date_value_expression(tuple_to, False)
                            else:
                                attributes[attr_name] = self._date_value_expression(tuple_to, date_as_datetime)
                        elif self.is_object_reference(tuple_to):
                            relations.append((obj_var, attr_name, tuple_to, field_name))
                        elif is_enum_value(tuple_to):
                            enum_value = get_enum_value(tuple_to)
                            attributes[attr_name] = f'"{enum_value}"'
                        elif self.is_str_value(tuple_to):
                            attributes[attr_name] = self._str_value_expression(tuple_to)
                        else:
                            attributes[attr_name] = get_primitive_value(tuple_to)

                attribute_mapping_parts = []
                for attr_name, attr_value in attributes.items():
                    attribute_mapping_parts.append(f"{attr_name!r}: {attr_value}")

                if for_editor:
                    kwargs_parts = []
                    for attr_name, attr_value in attributes.items():
                        if not attr_name.isidentifier() or keyword.iskeyword(attr_name):
                            logger.warning(
                                "Skipping attribute '%s' of object '%s' (editor mode): "
                                "not usable as a Python keyword argument",
                                attr_name, obj_name,
                            )
                            continue
                        kwargs_parts.append(f"{attr_name}={attr_value}")
                    if kwargs_parts:
                        code_lines.append(
                            f'{obj_var} = {class_name}("{obj_name}").attributes({", ".join(kwargs_parts)}).build()'
                        )
                    else:
                        code_lines.append(
                            f'{obj_var} = {class_name}("{obj_name}").attributes().build()'
                        )
                elif attribute_mapping_parts:
                    code_lines.append(
                        f'{obj_var} = {class_name}("{obj_name}").attributes(**{{{", ".join(attribute_mapping_parts)}}}).build()'
                    )
                else:
                    code_lines.append(
                        f'{obj_var} = {class_name}("{obj_name}").build()'
                    )

        code_lines.append("")

        if relations:
            code_lines.append("# Set relations between objects")

        paired_fields = self._pair_association_fields()
        seen_links = set()
        deduplicated_relations = []
        for from_var, relation_name, to_atom, field_name in relations:
            if to_atom not in created_objects:
                continue
            to_var = created_objects[to_atom]
            assoc_id = paired_fields.get(field_name, frozenset([field_name]))
            canonical = (frozenset([from_var, to_var]), assoc_id)
            if canonical in seen_links:
                continue
            seen_links.add(canonical)
            deduplicated_relations.append((from_var, relation_name, to_atom))

        relations = deduplicated_relations

        # Group relations by (from_var, relation_name) to handle multiplicity 'many'
        grouped_relations = {}
        for from_var, relation_name, to_atom in relations:
            if to_atom in created_objects:
                key = (from_var, relation_name)
                if key not in grouped_relations:
                    grouped_relations[key] = []
                grouped_relations[key].append(created_objects[to_atom])

        for (from_var, relation_name), to_vars in grouped_relations.items():
            unique_targets = sorted(set(to_vars))
            if for_editor:
                if not relation_name.isidentifier() or keyword.iskeyword(relation_name):
                    logger.warning(
                        "Skipping link '%s' from object '%s' (editor mode): "
                        "not usable as a Python attribute name",
                        relation_name, from_var,
                    )
                    continue
                for target in unique_targets:
                    code_lines.append(
                        f"{from_var}.{relation_name} = {target}"
                    )
            elif len(unique_targets) == 1:
                code_lines.append(
                    f"setattr({from_var}, {relation_name!r}, {unique_targets[0]})"
                )
            else:
                targets_expr = ", ".join(unique_targets)
                code_lines.append(
                    f"setattr({from_var}, {relation_name!r}, {{{targets_expr}}})"
                )

        if relations:
            code_lines.append("")

        code_lines.append("# Object Model instance")
        all_objects = ", ".join(created_objects.values())
        code_lines.append("object_model: ObjectModel = ObjectModel(")
        code_lines.append('    name="Object_Diagram",')
        code_lines.append(f"    objects={{{all_objects}}}")
        code_lines.append(")")
        return "\n".join(code_lines)




# ---------------------------------------------------------------------------
# Pure helpers for converting Alloy atoms/signatures into BUML object values
# ---------------------------------------------------------------------------

DATE_SIG_PATTERN = re.compile(r"^d\d{8}$")


def get_class_name(sig_label: str) -> str:
    """
    Extracts the class name from a signature label.
    Args:
        sig_label: label of the signature (e.g., 'this/Player')

    Returns:
        Class name (e.g., 'Player')
    """
    if "/" in sig_label:
        return sig_label.split("/")[-1]
    return sig_label


def remove_class_prefix(field_name: str, class_name: str) -> str:
    """
    Removes the class prefix from a field name.
    Args:
        field_name: field name (e.g., 'Player_name')
        class_name: class name (e.g., 'Player')

    Returns:
        Field name without prefix (e.g., 'name')
    """
    prefix = f"{class_name}_"
    if field_name.startswith(prefix):
        return field_name[len(prefix):]
    elif field_name.__contains__("_"):
        return field_name[field_name.index("_") + 1:]
    return field_name


def is_enum_value(atom_label: str) -> bool:
    """Determines if an atom is an enumeration value."""
    return atom_label.startswith("ENUM_")


def get_enum_value(atom_label: str) -> str:
    """
    Extracts the enumeration value from an atom label.
    Args:
        atom_label: atom label (e.g., 'ENUM_Position_CENTER$0')

    Returns:
        Enumeration value (e.g., 'CENTER')
    """
    # Format: ENUM_EnumName_VALUE$n
    parts = atom_label.split("_")
    if len(parts) >= 3:
        value = "_".join(parts[2:])  # take everything after ENUM_EnumName_
        # Remove suffix $n
        if "$" in value:
            value = value.split("$")[0]
        return value
    return atom_label


def get_primitive_value(atom_label: str, atom_type: str | None = None) -> Any:
    """
    Extracts the primitive value of an atom.
    Args:
        atom_label: atom label
        atom_type: expected type (Int, String, etc.)

    Returns:
        Converted primitive value
    """
    # Integers
    try:
        return int(atom_label)
    except ValueError:
        pass

    # Strings - return identifier without suffix
    if "$" in atom_label:
        base_name = atom_label.split("$")[0]
        return f'"{base_name}"'  # Return as quoted string

    return f'"{atom_label}"'


def get_date_value(atom_label: str) -> str:
    """
    Extracts the date value from an atom.

    Args:
        atom_label: atom label (e.g., 'Date0$0', 'd01012000$0' or 'Date$01')

    Returns:
        Date value as an ISO-8601 string with quotes (e.g., '"2000-01-01"')
    """
    base = get_class_name(atom_label.split("$")[0])
    if base in DATES_DICT:
        sig_id = DATES_DICT[base]
        return f'"{sig_id[5:9]}-{sig_id[1:3]}-{sig_id[3:5]}"'
    if DATE_SIG_PATTERN.match(base):
        return f'"{base[5:9]}-{base[1:3]}-{base[3:5]}"'
    return f'"{atom_label}"'


def char_to_letter(char_atom_label: str) -> str:
    """
    Extracts the letter of a Char atom.

    Args:
        char_atom_label: atom label (e.g., 'strings/z$0')

    Returns:
        Letter (e.g., 'z')
    """
    base = char_atom_label.split("$")[0]
    return get_class_name(base)


def get_str_value(index_char_pairs: list[tuple[str, str]]) -> str:
    """
    Decodes the value of a Str atom from its ``(index, Char atom)`` pairs.

    Args:
        index_char_pairs: list of ``(index_label, char_atom_label)`` pairs

    Returns:
        Decoded string value (e.g., 'zab')
    """
    ordered = sorted(index_char_pairs, key=lambda pair: int(pair[0]))
    return "".join(char_to_letter(char_atom) for _, char_atom in ordered)


def is_domain_class_name(class_name: str) -> bool:
    """Determines if *class_name* is a user domain class."""
    if not class_name:
        return False
    if is_enum_value(class_name) or class_name.startswith("ENUM_"):
        return False
    if class_name in ("Str", "Bool", "True", "False", "Date", "Ord"):
        return False
    return not DATE_SIG_PATTERN.match(class_name)
