"""
Safe AST-based loader for BUML Python files uploaded by users.

BUML files generated by our code builders are simple: a sequence of top-level
assignments and method calls that construct BUML metamodel instances via their
public constructors. There are no imports (they're stripped by the caller),
no function/class definitions, no control flow, no comprehensions.

This loader validates the AST against a strict allowlist of node types and
name references BEFORE executing it. Anything outside the allowlist raises
``SafeBumlLoaderError``. Only after validation passes do we compile and
``exec()`` the tree, with ``__builtins__`` zeroed out so attribute access on
primitives cannot reach dangerous helpers either.

This replaces the previous ``exec(cleaned_content, safe_globals, local_vars)``
pattern, which was bypassable via ``__class__.__mro__`` introspection on any
value inside ``safe_globals``.
"""
from __future__ import annotations

import ast
from typing import Any, Dict, Mapping, Set


class SafeBumlLoaderError(ValueError):
    """Raised when the BUML content contains disallowed constructs."""


# AST node types we accept. Anything not in this set is rejected.
#
# Rationale: these are the minimum nodes required to represent BUML files
# produced by besser.utilities.buml_code_builder: top-level assignments,
# constructor calls, literals, containers (list/tuple/set/dict), attribute
# chains for ``x.items.add(...)`` patterns, negative numeric literals, simple
# ``"a" + "b"`` string concatenation for composed names, and subscripting for
# indexing into dicts or lists.
_ALLOWED_NODE_TYPES: Set[type] = {
    ast.Module,
    ast.Expr,
    ast.Assign,
    # ``AnnAssign`` covers annotated assignments like ``x: Property = ...`` —
    # our code builder emits these heavily for readability. The annotation
    # itself is just a Name/Attribute that gets validated like any other
    # reference; the value side is the actual side-effecting part and is
    # validated normally.
    ast.AnnAssign,
    ast.Call,
    ast.Name,
    ast.Attribute,
    ast.Constant,
    ast.List,
    ast.Tuple,
    ast.Set,
    ast.Dict,
    ast.keyword,
    ast.BinOp,
    ast.UnaryOp,
    ast.Subscript,
    ast.Load,
    ast.Store,
    # Operator node classes that appear as children of BinOp / UnaryOp.
    # The actual *operator* is validated separately (only Add for BinOp,
    # USub/UAdd/Not for UnaryOp) via the _ALLOWED_BINOPS and
    # _ALLOWED_UNARY_OPS checks below. We have to list every operator class
    # we accept here because AST traversal visits the operator node too.
    ast.Add,
    ast.USub,
    ast.UAdd,
    ast.Not,
}

# Inside ``UnaryOp`` we only allow the operators needed for signed numeric
# literals (``-1``, ``+1``) and the occasional boolean negation flag.
_ALLOWED_UNARY_OPS: Set[type] = {ast.USub, ast.UAdd, ast.Not}

# ``BinOp`` is strictly limited to string/numeric addition because BUML code
# occasionally concatenates identifier parts (e.g. ``prefix + name``). All
# other binary operators (shifts, bitwise ops, etc.) are rejected.
_ALLOWED_BINOPS: Set[type] = {ast.Add}


def _is_dunder(name: str) -> bool:
    """Return True for names starting with ``_`` (includes dunders)."""
    return name.startswith("_")


def _attribute_root_name(node: ast.AST) -> str | None:
    """
    Walk an ``Attribute`` chain back to its root ``Name`` node and return
    that name. Returns ``None`` if the root is not a simple Name (e.g. the
    chain starts from a Call or a Subscript).
    """
    current = node
    while isinstance(current, ast.Attribute):
        current = current.value
    if isinstance(current, ast.Name):
        return current.id
    return None


def _validate_node(
    node: ast.AST,
    allowed_names: Mapping[str, Any],
    declared_vars: Set[str],
) -> None:
    """
    Recursively validate ``node``. Raises ``SafeBumlLoaderError`` on anything
    outside our allowlist.

    ``allowed_names`` is the fixed set of names that may appear as the root
    of any name reference (the injected BUML classes + helper constants).
    ``declared_vars`` is the set of variable names assigned earlier in this
    same file; a reference to ``x.foo()`` is only allowed if ``x`` is in
    ``allowed_names`` or ``declared_vars``.
    """
    node_type = type(node)
    if node_type not in _ALLOWED_NODE_TYPES:
        raise SafeBumlLoaderError(
            f"Disallowed AST node: {node_type.__name__}"
        )

    if isinstance(node, ast.BinOp):
        if type(node.op) not in _ALLOWED_BINOPS:
            raise SafeBumlLoaderError(
                f"Disallowed binary operator: {type(node.op).__name__}"
            )

    if isinstance(node, ast.UnaryOp):
        if type(node.op) not in _ALLOWED_UNARY_OPS:
            raise SafeBumlLoaderError(
                f"Disallowed unary operator: {type(node.op).__name__}"
            )

    if isinstance(node, ast.Attribute):
        if _is_dunder(node.attr):
            raise SafeBumlLoaderError(
                f"Access to dunder/underscore attribute is forbidden: {node.attr!r}"
            )
        # The root of the attribute chain must resolve to an allowed name or
        # a previously declared variable. This blocks ``os.system`` style
        # calls when ``os`` is not in the allowed dict.
        root = _attribute_root_name(node)
        if root is not None:
            if root not in allowed_names and root not in declared_vars:
                raise SafeBumlLoaderError(
                    f"Attribute access on unknown name: {root!r}"
                )

    if isinstance(node, ast.Name):
        # Store-context names are fine (we collect them separately); only
        # Load-context references need to resolve to something we allow.
        if isinstance(node.ctx, ast.Load):
            if node.id not in allowed_names and node.id not in declared_vars:
                raise SafeBumlLoaderError(
                    f"Reference to unknown name: {node.id!r}"
                )
            if _is_dunder(node.id):
                raise SafeBumlLoaderError(
                    f"Reference to underscore/dunder name is forbidden: {node.id!r}"
                )

    if isinstance(node, ast.Call):
        func = node.func
        if isinstance(func, ast.Name):
            if func.id not in allowed_names and func.id not in declared_vars:
                raise SafeBumlLoaderError(
                    f"Call to unknown function: {func.id!r}"
                )
        elif isinstance(func, ast.Attribute):
            # Method call like ``domain_model.types.add(cls1)``.
            # Both the dunder check and the root check are handled by the
            # generic Attribute validation above; nothing extra here.
            pass
        else:
            raise SafeBumlLoaderError(
                "Only calls to named functions or attribute chains are allowed"
            )

    # Recurse into children. Use ``iter_child_nodes`` so we cover all
    # AST-significant children without hitting string fields.
    for child in ast.iter_child_nodes(node):
        _validate_node(child, allowed_names, declared_vars)


def _collect_assigned_names(module: ast.Module) -> Set[str]:
    """
    Pre-scan the module for top-level assignments and collect every variable
    name they bind. This lets later expressions reference ``domain_model``,
    ``cls1``, etc. even if the assignment comes lexically later in the file
    (which doesn't happen for BUML output, but is safe to permit).
    """
    names: Set[str] = set()
    for stmt in module.body:
        if isinstance(stmt, ast.Assign):
            for target in stmt.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
                elif isinstance(target, (ast.Tuple, ast.List)):
                    for element in target.elts:
                        if isinstance(element, ast.Name):
                            names.add(element.id)
        elif isinstance(stmt, ast.AnnAssign):
            # Annotated assignments only have a single target.
            if isinstance(stmt.target, ast.Name):
                names.add(stmt.target.id)
    return names


def safe_load_buml(
    content: str,
    allowed_names: Mapping[str, Any],
) -> Dict[str, Any]:
    """
    Parse ``content`` as Python, validate against the allowlist, and execute
    the validated tree in a frozen namespace. Returns the dict of local
    variables produced by execution.

    Parameters
    ----------
    content:
        The cleaned BUML source (imports already stripped by the caller).
    allowed_names:
        Mapping of names that may appear at the top level of an expression.
        Typically the BUML classes and helper constants the file constructs.

    Returns
    -------
    dict
        The local variables produced during execution, for the caller to
        inspect and pluck out the model instance.

    Raises
    ------
    SafeBumlLoaderError
        If the AST contains a disallowed construct.
    SyntaxError
        If the content is not parseable Python.
    """
    tree = ast.parse(content, mode="exec")

    # Only module-level statements are allowed to be Assign or Expr. Things
    # like ``FunctionDef``, ``ClassDef``, ``Import``, ``If``, ``For`` never
    # appear in our emitted BUML and are not in ``_ALLOWED_NODE_TYPES``, so
    # they'll be caught during recursive validation anyway. Double-check here
    # to fail fast with a clear message.
    for stmt in tree.body:
        if not isinstance(stmt, (ast.Assign, ast.AnnAssign, ast.Expr)):
            raise SafeBumlLoaderError(
                f"Top-level statement not allowed: {type(stmt).__name__}"
            )

    declared_vars = _collect_assigned_names(tree)

    # Reject any overlap between declared vars and allowed builtins that
    # contain characters forbidden elsewhere (e.g. starting with ``_``).
    for name in declared_vars:
        if _is_dunder(name):
            raise SafeBumlLoaderError(
                f"Assignment to underscore/dunder name is forbidden: {name!r}"
            )

    _validate_node(tree, allowed_names, declared_vars)

    # Re-parse with location info preserved (ast.parse already did this, but
    # fix_missing_locations is cheap insurance for manually constructed ASTs).
    ast.fix_missing_locations(tree)

    code = compile(tree, filename="<buml>", mode="exec")

    # Execute with an empty ``__builtins__`` so user content cannot reach
    # any built-in helpers; everything it needs must be in ``allowed_names``.
    globals_ns: Dict[str, Any] = {"__builtins__": {}}
    globals_ns.update(allowed_names)
    locals_ns: Dict[str, Any] = {}
    exec(code, globals_ns, locals_ns)  # noqa: S102 - AST pre-validated above
    return locals_ns
