name: Build and Push Docker Images to Artifactory

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create .env file dynamically
      run: |
        echo DEPLOYMENT_URL=https://editor.besser-pearl.org > .env
        echo BACKEND_URL=https://editor.besser-pearl.org/besser_api >> .env
        echo APOLLON_REDIS_DIAGRAM_TTL=30d >> .env

    - name: Login to Artifactory
      uses: docker/login-action@v3
      with:
        registry: artefacts.list.lu
        username: ${{ secrets.ARTIFACTORY_USER }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}

    - name: Build Docker images via docker compose
      run: docker compose build

    - name: Push backend image
      run: docker push artefacts.list.lu/besser/web_modeling_editor/backend:latest

    - name: Push frontend image
      run: docker push artefacts.list.lu/besser/web_modeling_editor/frontend:latest
